export type SeedEntry = { slug: string; body: string };

const SLUG_RE = /^[a-z0-9-]+$/;
const MAX_TAG_ATTEMPTS = 64;

const HEADER = [
	'-- Generated by scripts/generate-content-migration.ts from content/provincias/*.md.',
	'-- Do not edit by hand: regenerate with `pnpm content:seed-sql`.',
	'-- `on conflict do nothing` is deliberate: re-running never overwrites edits made from the UI.'
].join('\n');

/**
 * Picks a dollar-quote delimiter that cannot terminate the string early.
 * The delimiter must not occur in the body, nor form across the body/closer boundary.
 */
function pickDelimiter(body: string, slug: string): string {
	for (let i = 0; i <= MAX_TAG_ATTEMPTS; i++) {
		const delim = i === 0 ? '$c$' : `$c${i}$`;
		if (`${body}${delim}`.indexOf(delim) === body.length) return delim;
	}
	throw new Error(`No safe dollar-quote tag for "${slug}"`);
}

/** Deterministic SQL that seeds `provincia_contenido` without ever overwriting existing rows. */
export function buildSeedSql(entries: readonly SeedEntry[]): string {
	const seen = new Set<string>();
	for (const { slug } of entries) {
		if (!SLUG_RE.test(slug)) throw new Error(`Invalid slug: ${JSON.stringify(slug)}`);
		if (seen.has(slug)) throw new Error(`Duplicate slug: ${slug}`);
		seen.add(slug);
	}
	const statements = [...entries]
		.sort((a, b) => (a.slug < b.slug ? -1 : a.slug > b.slug ? 1 : 0))
		.map(({ slug, body }) => {
			const q = pickDelimiter(body, slug);
			return (
				`insert into public.provincia_contenido (provincia_id, body) ` +
				`select id, ${q}${body}${q} from public.provincias where slug = '${slug}' ` +
				`on conflict (provincia_id) do nothing;`
			);
		});
	return [HEADER, ...statements].join('\n\n') + '\n';
}
