-- Generated by scripts/generate-content-migration.ts from content/provincias/*.md.
-- Do not edit by hand: regenerate with `pnpm content:seed-sql`.
-- `on conflict do nothing` is deliberate: re-running never overwrites edits made from the UI.

insert into public.provincia_contenido (provincia_id, body) select id, $c$El Oro ocupa el suroeste de la Costa ecuatoriana, donde la llanura frente al Pacífico da paso a los primeros relieves andinos. Su capital es Machala, que el plan provincial llama «Capital Bananera del Mundo». Fue provincializada en 1884, el 23 de abril, y hoy reúne 14 cantones. Su superficie ronda los 5 800 km², aunque las cifras oficiales difieren un poco entre sí. Limita con Guayas y Azuay al norte, con Loja al sur y al este y con el Pacífico al oeste; además comparte frontera con Perú.

### De los manglares a los 3 900 metros

En pocos kilómetros el terreno sube del nivel del mar a unos 3 900 m. Según el INABIO, es el punto donde los Andes se aproximan más al océano. La costa noroccidental, entre 0 y 50 m, ocupa cerca del 38 % del territorio; el resto son faldas occidentales que llegan a 3 590 m en el cerro Chilla-Cocha.

El plan provincial describe una costa de verano seco e invierno lluvioso, con 20 a 26 °C, y una zona alta más lluviosa, de 10 a 18 °C.

En Arenillas y Huaquillas, una reserva ecológica protege bosque seco tumbesino; el INABIO le atribuye 13 170 ha. En el límite con Loja está Puyango, bosque protector desde 1987 y patrimonio cultural nacional desde 1988, con 2 659 ha de troncos fósiles de unos 100 millones de años.

### Banano, camarón y oro

El censo de 2022 contó 714 592 habitantes, cerca del 78 % en áreas urbanas. Machala suma 306 309, y le siguen Pasaje, Santa Rosa, El Guabo y Huaquillas.

El banano es la actividad más significativa: según la prefectura, equivale a cerca del 30 % de la economía provincial, y su auge arrancó en la década de 1940. También pesan el cacao, el café y el camarón; El Oro es la segunda provincia del país en este último rubro, que empezó en 1966. Puerto Bolívar, junto a Machala, es el segundo puerto marítimo después del de Guayaquil. En Zaruma y Portovelo sigue la minería de oro, y el comercio se apoya en la frontera con Perú.

### Qué ver y cuándo son las fiestas

Frente a la costa se extiende el archipiélago de Jambelí, con manglar y playa, a unos 30 minutos en lancha desde Puerto Bolívar o Puerto Hualtaco. Más lejos queda la isla Santa Clara, refugio de aves marinas y lobos marinos; la guía oficial de turismo sitúa allí la temporada de ballenas entre agosto y octubre.

Zaruma, en la parte alta, fue declarada Patrimonio Cultural del Estado en 1990 y consta desde 1998 en la lista indicativa de la UNESCO. Celebra en julio las fiestas de la Virgen del Carmen; el programa de 2025 iba del 4 al 27.

En septiembre Machala organiza la Feria Mundial del Banano, que según medios locales forma parte de las fiestas de la Virgen de la Merced; su 61.ª edición se anunció para el 17 al 20 de septiembre de 2026. Machala se atiende desde el Aeropuerto Regional de Santa Rosa, operativo desde 2008.

### Fuentes

- [Gobierno Provincial de El Oro: PDYOT 2024-2027](https://datos.eloro.gob.ec/PDF%20PDYOT/PDYOT%20-%202024%20-%202027.pdf)
- [INEC: Censo 2022, ficha de El Oro](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_El-Oro.pdf)
- [CONGOPE: provincia de El Oro](https://www.congope.gob.ec/provincia-de-el-oro/)
- [INABIO y GAD de El Oro: propuesta de corredor ecológico, 2019](http://inabio.biodiversidad.gob.ec/wp-content/uploads/2020/10/Libro%20Propuesta%20ACP%20y%20Corredor%20Ecol%C3%B3gico%20de%20la%20provincia%20de%20El%20Oro%202019.pdf)
- [El Universo: fósiles de Puyango](https://www.eluniverso.com/noticias/2019/12/06/nota/7637105/bosque-petrificado-puyango-historia-oro-fosiles-loja/)
- [El Universo: Zaruma, riqueza cultural](https://www.eluniverso.com/noticias/2020/11/25/nota/8061649/riqueza-cultural-destaca-bicentenaria-zaruma/)
- [Ecuador Travel: turismo en Santa Rosa, El Oro](https://ecuador.travel/turismo-en-santa-rosa-el-oro/)
- [Municipio de Zaruma: programa de festividades 2025](https://www.zaruma.gob.ec/assets/18_PROGRAMA.%20DE%20FESTIVIDADES%202025.pdf)
- [Machala Móvil: 61.ª Feria Mundial del Banano](https://machalamovil.com/prefecta-karina-torres-inaugura-este-jueves-la-edicion-61-de-la-feria-mundial-del-banano/)
$c$ from public.provincias where slug = 'el-oro' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Esmeraldas ocupa el extremo noroccidental del Ecuador, donde el país toca el Pacífico y la frontera con Colombia. Su capital es la ciudad de Esmeraldas y se divide en siete cantones: Esmeraldas, Atacames, Eloy Alfaro, Muisne, Quinindé, Ríoverde y San Lorenzo. Al este colinda con Carchi e Imbabura, hacia el sureste con Pichincha, y al sur con Manabí y Santo Domingo de los Tsáchilas. Su superficie ronda los 15 800 km², aunque las cifras oficiales difieren un poco.

### Una población afroecuatoriana y diversa

El censo de 2022 del INEC contó 553 900 habitantes, algo más de la mitad en el campo (55,1 %). El cantón Esmeraldas reúne a 211 848 personas y Quinindé, el segundo en tamaño, a 126 841. Más de la mitad de los habitantes, el 53,8 %, se identificó como afroecuatoriana; el 39,5 % como mestiza y el 3,4 % como indígena.

Esa mezcla se refleja en la música. La marimba, unida a los cantos y bailes tradicionales del Pacífico sur colombiano y esmeraldeño, figura desde 2015 en la Lista Representativa del Patrimonio Cultural Inmaterial de la UNESCO. El Museo y Centro Cultural Esmeraldas, abierto en 1979, documenta las culturas afroesmeraldeña, chachi, awá y épera, además de piezas arqueológicas tolitas, teaone y atacameñas.

### Manglares y bosques protegidos

En el norte, la Reserva Ecológica Manglares Cayapas-Mataje protege el estuario de los dos ríos que le dan nombre, en los cantones San Lorenzo y Eloy Alfaro. La guía de visitantes del Ministerio del Ambiente, publicada en 2024, señala que sus manglares alcanzan hasta 60 m de altura, y los describe como los más altos del mundo. Las salidas a observar aves o delfines dependen de la marea.

Más al sur, la Reserva Ecológica Mache Chindul resguarda bosques húmedos y secos de la cordillera del mismo nombre, con la laguna de Cube y la cascada Colorado como puntos de referencia; el acceso parte de Quinindé. Hacia el este, la provincia comparte con Imbabura el Parque Nacional Cotacachi-Cayapas.

### Playas, mesa y fechas

La costa reúne balnearios de carácter distinto. Atacames es la playa más concurrida y tiene malecón con restaurantes; Tonsupa resulta más tranquila y familiar; Mompiche es un pueblo pesquero con olas apreciadas por quienes practican surf, y Súa, una aldea pesquera. En la mesa abundan el encocado, el arroz con concha, la cazuela de mariscos y la tonga, preparada con salsa de maní y cocida dentro de una hoja de plátano.

El 5 de agosto se conmemora la independencia de Esmeraldas, con desfile cívico-militar y sesión solemne; en 2025 se cumplieron 205 años. En noviembre la Prefectura recuerda la provincialización, que fija el 20 de noviembre de 1847 como fecha oficial.

### Cómo llegar

Desde Quito hay dos rutas por la vía E20: una por Calacalí y La Independencia, y otra por Santo Domingo. En Tachina, junto a la capital provincial, se encuentra el aeropuerto Carlos Concha Torres; su servicio comercial ha sido intermitente y la Dirección General de Aviación Civil es la fuente para saber si hay vuelos.

### Fuentes

- [CONGOPE: provincia de Esmeraldas](https://www.congope.gob.ec/provincia-de-esmeraldas/)
- [Prefectura de Esmeraldas: la provincia](https://prefecturadeesmeraldas.gob.ec/index.php/provincia-de-esmeraldas/)
- [Prefectura de Esmeraldas: provincialización](https://www.prefecturadeesmeraldas.gob.ec/web/assets/provincializacion.pdf)
- [INEC: Censo 2022, ficha de Esmeraldas](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Esmeraldas.pdf)
- [Gobierno Provincial de Pichincha: información general](https://www.pichincha.gob.ec/pichincha/datos-de-la-provincia/95-informacion-general)
- [UNESCO: marimba, cantos y bailes tradicionales](https://ich.unesco.org/en/RL/marimba-music-traditional-chants-and-dances-from-the-colombia-south-pacific-region-and-esmeraldas-province-of-ecuador-01099)
- [Ministerio del Ambiente: guía de visitantes de la Costa, 2024](https://www.ambienteyenergia.gob.ec/wp-content/uploads/sites/2/downloads/2024/11/COSTA-1-OK.pdf)
- [Museo y Centro Cultural Esmeraldas](https://educacion.gob.ec/cultura/museo-y-centro-cultural-esmeraldas/)
- [Ecuador Travel: Esmeraldas](https://ecuador.travel/esmeraldas-donde-la-naturaleza-y-la-cultura-afroecuatoriana-te-esperan/)
- [AME: fiestas de independencia de Esmeraldas](https://ame.gob.ec/esmeraldas-celebra-a-lo-grande-sus-fiestas-de-independencia/)
- [DGAC: vuelos en el aeropuerto Carlos Concha Torres](https://www.aviacioncivil.gob.ec/se-retoman-vuelos-desde-el-aeropuerto-carlos-concha-torres-de-esmeraldas/)
- [Ministerio del Ambiente: Parque Nacional Cotacachi-Cayapas](https://www.ambienteyenergia.gob.ec/ambiente/el-parque-nacional-cotacachi-cayapas-conmemoro-sus-53-anos-de-creacion/)
$c$ from public.provincias where slug = 'esmeraldas' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Guayas ocupa el suroeste de la Costa ecuatoriana y reúne 25 cantones alrededor de Guayaquil, su capital. Allí el río que le da nombre se abre hacia el Golfo de Guayaquil, y esa mezcla de agua dulce, manglar y mar marca buena parte de su vida. Según la fuente, la superficie va de unos 15 500 a unos 15 900 km². Hasta 2007 tenía también los cantones de Santa Elena, Salinas y La Libertad, que ese año formaron una provincia propia; Guayas conservó su litoral, con Playas, Posorja, la isla Puná y el Golfo. Sus vecinas son Manabí, Santa Elena, Los Ríos, Bolívar, Chimborazo, Cañar, Azuay y El Oro.

### Llanuras y ríos

Más de la mitad del territorio son llanuras aluviales que casi siempre se elevan menos de 5 m. Las zonas más altas, al este de Bucay y El Triunfo y en Naranjal, van de 200 a 300 m. La cuenca del Guayas abarca cerca del 90 % del territorio provincial; el Daule y el Babahoyo figuran entre sus afluentes principales. Las temperaturas se mueven entre 20 y 28 °C. En los terrenos planos domina el arroz; en las partes onduladas, la caña, el banano y la soya.

### Habitantes y economía

El censo de 2022 del INEC contó 4 391 923 personas, lo que hace de Guayas la más poblada del país; el 85,3 % vive en áreas urbanas. Guayaquil suma 2 746 403 habitantes, seguida de Durán (303 910), Daule (222 446) y Milagro (195 943).

La manufactura es la mayor actividad según el valor agregado de 2018, con el 21,1 % del total. La Prefectura recoge además una cifra de la Cámara de Industrias de Guayaquil: a fines de 2017 la provincia albergaba el 41 % de las empresas del país. Milagro destaca por el azúcar y sus derivados, Yaguachi por el arroz, el cacao y la caña, y en Playas pesan la pesca, el camarón y el turismo.

### Puertos y accesos

El puerto de aguas profundas de Posorja empezó a operar en agosto de 2019, con un canal de 16,5 m de profundidad. El aeropuerto José Joaquín de Olmedo, al norte de Guayaquil, inauguró su terminal actual el 27 de julio de 2006. El puente de la Unidad Nacional enlaza Guayaquil con Durán, y Playas está a unos 97 km de Guayaquil.

### Qué ver y fiestas

El Malecón Simón Bolívar se extiende 2,5 km junto al río, con la Rotonda y la Torre Morisca. Las Peñas, barrio histórico declarado patrimonio nacional en 1982, sube al cerro Santa Ana por 444 escalones. Entre los espacios naturales figuran la isla Santay, sitio Ramsar entre Guayaquil y Durán, el bosque seco de Cerro Blanco y Manglares Churute, un área protegida.

La Prefectura da 1547 como fecha de la fundación definitiva de Guayaquil. Yaguachi celebra a San Jacinto el 16 de agosto, Milagro festeja su cantonización el 17 de septiembre, y en Playas hay Carnaval en febrero y fiesta de San Pedro en junio. La temporada de playa va, según la Prefectura, de enero a abril.

### Fuentes

- [CONGOPE: provincia de Guayas](https://www.congope.gob.ec/provincia-de-guayas/)
- [Prefectura del Guayas: PDOT 2021](https://guayas.gob.ec/wp-content/uploads/2021/08/2021-08-20-PDOT-Guayas.pdf)
- [INEC: Censo 2022, ficha de Guayas](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Guayas.pdf)
- [INEC: Censo 2022, ficha de Pichincha](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Pichincha.pdf)
- [Prefectura del Guayas: cantón Guayaquil](https://guayas.gob.ec/cantones-2/guayaquil/)
- [Prefectura del Guayas: cantón Playas](https://guayas.gob.ec/cantones-2/playas/)
- [Prefectura del Guayas: cantón Durán](https://guayas.gob.ec/cantones-2/duran/)
- [Prefectura del Guayas: cantón Milagro](https://guayas.gob.ec/cantones-2/milagro/)
- [Prefectura del Guayas: cantón Yaguachi](https://guayas.gob.ec/cantones-2/yaguachi/)
- [Municipio de Yaguachi: festividades](https://municipiodeyaguachi.gob.ec/turismo-festividades/)
- [Gobierno de Santa Elena: provincialización](https://www.santaelena.gob.ec/index.php/provincializacion/23santa-elena/santa-elena)
- [Ministerio de Transporte: puerto de Posorja](https://www.mit.gob.ec/puerto-de-aguas-profundas-de-posorja-cumple-un-ano-de-operatividad-y-se-consolida-como-el-primer-puerto-inteligente-de-ecuador/)
- [TAGSA: terminal del aeropuerto de Guayaquil](https://www.tagsa.aero/tagsa-terminal.html)
- [Municipio de Guayaquil: Malecón 2000](https://guayaquil.gob.ec/malecon-2000-guayaquil-naturaleza-entretenimiento/)
- [Guayaquil Turismo](https://turismo.guayaquil.gob.ec/es)
- [Ecuador Chequea: Manglares Churute](https://ecuadorchequea.com/manglares-churute-la-reserva-natural-que-ecuador-abandono/)
$c$ from public.provincias where slug = 'guayas' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Imbabura ocupa el norte de la Sierra ecuatoriana y tiene a Ibarra como capital. Creada en 1824, se divide en seis cantones: Ibarra, Antonio Ante, Cotacachi, Otavalo, Pimampiro y San Miguel de Urcuquí. Sus vecinas son Carchi, en el norte; Pichincha, en el sur; Sucumbíos, en el este, y Esmeraldas, en el oeste. Abarca unos 4 790 km², según el plan de desarrollo provincial.

### Volcanes y lagos

La mayor altura de Imbabura corresponde al Cotacachi, un volcán inactivo de 4 939 m. Otro gran volcán es el Imbabura, de cerca de 4 620 m, que el Instituto Geofísico considera potencialmente activo; su última erupción data de hace unos 8 000 años. En sus faldas se extiende el lago San Pablo, que el Geoparque describe como el mayor lago natural del país.

El plan provincial cuenta 27 lagunas. Entre ellas está Yahuarcocha, a unos 4 km del centro de Ibarra, cuyo nombre kichwa significa «lago de sangre», y Cuicocha, en una caldera de unos 3,5 km de diámetro nacida de una erupción explosiva hace unos 3 100 años. Desde 2019 el territorio forma parte del Geoparque Mundial UNESCO Imbabura, de 479 100 ha.

### Clima

La altura reparte los climas: cálido y seco en el Chota, templado en las cabeceras de los valles, frío en los volcanes y cálido húmedo en Intag y Lita. La temperatura media anual va de 12 a 14 °C en Otavalo a 22 a 24 °C en Lita. Según el INAMHI, citado en el plan provincial, llueve sobre todo de diciembre a mayo, y de junio a noviembre los cielos suelen despejarse más.

### Habitantes y economía

El censo de 2022 contó 469 879 habitantes, el 52,3 % en zonas urbanas. Ibarra reúne a 217 469 y Otavalo a 114 303. Un 64,9 % se identificó como mestizo, un 28,0 % como indígena y un 5,8 % como afroecuatoriano. En el Chota, las comunidades afrodescendientes llegaron durante la colonia a las plantaciones de caña y conservan la música bomba.

En 2022 los servicios ocupaban al 56,9 % de los empleados y la agricultura al 18,4 %. Por superficie, en 2023 predominaron el maíz suave seco, el fréjol, la caña de azúcar, el plátano y el aguacate. En 2021, el 33,21 % del territorio estaba bajo concesión minera.

### Qué ver

El Parque Nacional Cotacachi-Cayapas aporta 39 937,30 ha dentro de Imbabura. En Otavalo, la cascada de Peguche cae unos 20 m en un bosque protector que fue lugar ritual indígena previo al Inti Raymi, y la feria de la Plaza de los Ponchos es otro referente. Chachimbiro ofrece termas con aguas de 25 a 61 grados. Angochagua-Huaraczapas fue distinguido en 2022 como Mejor Pueblo Turístico por ONU Turismo, y San Antonio de Ibarra, Cotacachi y Pimampiro figuran como Pueblos Mágicos.

En Ibarra, a finales de abril se celebra El Retorno, que evoca la vuelta a la ciudad reconstruida en 1872, tras el terremoto de 1868.

### Fuentes

- [Prefectura de Imbabura: PDOT 2023-2027 (reformado)](https://www.imbabura.gob.ec/documentos/2026/pdot/PDOT-2023-2027_reformado.pdf)
- [INEC: Censo 2022, ficha de Imbabura](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Imbabura.pdf)
- [Prefectura de Imbabura: reseña histórica](https://www.imbabura.gob.ec/index.php/imbabura/resena-historica)
- [Prefectura de Imbabura: datos generales](https://www.imbabura.gob.ec/index.php/imbabura/datos-generales)
- [Instituto Geofísico: volcán Imbabura](https://www.igepn.edu.ec/imbabura)
- [Geoparque Imbabura: Cotacachi-Cuicocha](https://geoparque.imbabura.gob.ec/index.php/geoproductos/cotacachi-cuicocha/)
- [Geoparque Imbabura: complejo volcánico Imbabura-Cubilche](https://geoparque.imbabura.gob.ec/index.php/geoproductos/complejo-volcanico-imbabura-cubilche/)
- [Geoparque Imbabura: lago San Pablo y cascada de Peguche](https://geoparque.imbabura.gob.ec/index.php/geoproductos/lago-san-pablo-cascada-de-peguche/)
- [Geoparque Imbabura: laguna de Yahuarcocha](https://geoparque.imbabura.gob.ec/index.php/geoproductos/laguna-de-yahuarcocha/)
- [Geoparque Imbabura: valle del Chota](https://geoparque.imbabura.gob.ec/index.php/geoproductos/valle-del-chota/)
- [Geoparque Imbabura: complejo termal de Chachimbiro](https://geoparque.imbabura.gob.ec/index.php/geoproductos/complejo-termal-chachimbiro)
- [Geoparque Imbabura: valle de Intag](https://geoparque.imbabura.gob.ec/index.php/geoproductos/valle-de-intag/)
- [Geoparque Imbabura: Angochagua](https://geoparque.imbabura.gob.ec/index.php/geoproductos/angochagua)
- [UNESCO: Geoparque Mundial Imbabura](https://www.unesco.org/en/iggp/imbabura-unesco-global-geopark)
- [Municipio de Ibarra](https://www.ibarra.gob.ec)
- [Municipio de Otavalo](https://www.otavalo.gob.ec)
$c$ from public.provincias where slug = 'imbabura' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Los Ríos es una provincia de llanura y de agua, en el Litoral ecuatoriano. Babahoyo es su capital y la provincia se reparte en trece cantones: Baba, Babahoyo, Buena Fe, Mocache, Montalvo, Palenque, Puebloviejo, Quevedo, Quinsaloma, Urdaneta, Valencia, Ventanas y Vinces. Según el CONGOPE, su superficie ronda los 7 200 km². Limita con Santo Domingo de los Tsáchilas, Cotopaxi, Bolívar y Guayas, y Manabí queda hacia el noroeste. El eje fluvial es el Babahoyo, formado por los aportes del Catarama, el San Pablo, el Zapotal, el Puebloviejo y el Vinces. Al juntarse con el Daule, da origen al Guayas.

### Historia y habitantes

Babahoyo proclamó su independencia en octubre de 1820, un día 11. Cuatro décadas después, en octubre de 1860, un día 6, un decreto de Gabriel García Moreno creó la provincia y dejó a Babahoyo como capital provisional.

El censo de 2022 del INEC contó 898 652 habitantes, frente a 778 135 en 2010. La ciudad más poblada no es la capital: el cantón Quevedo reúne 206 008 personas y supera a Babahoyo, con 178 509. Les sigue Vinces, con 80 909.

### Una economía de cultivos

La tierra explica buena parte de la identidad provincial. Según la Encuesta de Superficie y Producción Agropecuaria Continua (ESPAC) de 2024, Los Ríos aportó el 39,8 % de la producción nacional de banano, el 30,4 % del cacao, el 28,6 % de la palma africana y el 43,8 % del maíz duro. En el cantón Babahoyo, la población se dedica sobre todo al arroz y al banano.

### Agua y bosque

El humedal Abras de Mantequilla, en Vinces, Baba y Puebloviejo, figura como sitio Ramsar desde el año 2000, con unas 22 500 ha, según el registro internacional. Otro refugio verde es Jauneche, en el cantón Palenque: un Bosque Protector de 138 ha, declarado en 1987 y vinculado a una estación científica de la Universidad de Guayaquil.

### Qué ver y cuándo celebrar

En Babahoyo, la Casa de Olmedo se asocia con el poeta José Joaquín de Olmedo, y el malecón 9 de Octubre bordea el río, con viviendas flotantes. A unos 8,5 km de la ciudad se levanta el cerro Cacharí, un macizo rocoso que sobresale en medio de la llanura aluvial. También hay un sitio arqueológico, La Tola. En Valencia, el CONGOPE destaca un río de aguas claras apto para la pesca, los paseos en bote y las caminatas.

La cocina local se apoya en el río. El CONGOPE menciona el encanutado de bocachico, un pescado asado dentro de una caña, el bollo de pescado con salsa de maní y la chicha de chontilla.

El calendario reúne varias fechas:

- 27 de mayo: cantonización de Babahoyo.
- Septiembre: fiestas de la Virgen de la Merced, con procesión el 24 en Babahoyo y novena del 15 al 23 en Quevedo.
- 6 de octubre: aniversario de la provincia.
- Octubre: rodeo montubio en varios sitios de la provincia.

### Fuentes

- [CONGOPE: provincia de Los Ríos](https://www.congope.gob.ec/provincia-de-los-rios/)
- [CONGOPE: turismo en Los Ríos](https://www.congope.gob.ec/turismo-los-rios/)
- [Municipio de Babahoyo: historia](https://babahoyo.gob.ec/historia)
- [AME: cantón Babahoyo](https://repositorio.ame.gob.ec/canton-babahoyo/)
- [AME: Jauneche, un bosque protector del cantón Palenque](https://repositorio.ame.gob.ec/jauneche-un-bosque-protector-que-engalana-al-canton-palenque/)
- [INEC: Censo 2022, ficha de Los Ríos](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Los-Rios.pdf)
- [INEC: presentación de resultados ESPAC 2024](https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_agropecuarias/espac/2024/Presentacion_de_resultados_ESPAC_2024.pdf)
- [Ramsar: Abras de Mantequilla](https://rsis.ramsar.org/es/ris/1023)
- [Municipio de Quevedo: cronograma de actividades](https://quevedo.gob.ec/cronograma-de-actividades-religiosas-y-culturales/)
$c$ from public.provincias where slug = 'los-rios' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Manabí se extiende sobre la costa central del Ecuador, de cara al Pacífico, y tiene a Portoviejo como capital. Se divide en 22 cantones y limita con Esmeraldas al norte, con Santa Elena al sur y con Santo Domingo de los Tsáchilas, Los Ríos y Guayas al este. Su superficie ronda los 19 500 km², aunque las cifras oficiales difieren un poco entre sí. Uno de sus cantones se llama Pichincha.

### Estaciones y paisajes protegidos

Según el plan de desarrollo provincial, hay una estación lluviosa, de enero a mayo, y otra seca, de junio a diciembre. En el litoral semiárido la temperatura suele moverse entre 20 y 26 °C; en la zona central, la más extensa, supera los 24 °C durante la época seca; y en el noreste húmedo oscila entre 15 y 24 °C, con lluvias de 1 000 a 2 000 mm anuales.

El Parque Nacional Machalilla reúne bosques secos y ambientes marinos, con playas como Los Frailes, varios islotes y la Isla de la Plata, que forma parte del parque y no es una reserva aparte. En la desembocadura del río Chone, el Refugio de Vida Silvestre Isla Corazón y Fragata protege un manglar donde, según el Ministerio del Ambiente, anidan de las mayores colonias de fragatas del país.

### Habitantes y trabajo

El censo de 2022 del INEC contó 1 592 840 personas, lo que convierte a Manabí en la tercera provincia más poblada. El 58 % vive en áreas urbanas, y Portoviejo, con 322 925 habitantes, y Manta, con 271 145, son los cantones más numerosos.

La economía descansa sobre el campo y el mar. Entre los cultivos, el cacao ocupa la mayor superficie y el maíz aporta el mayor volumen. En ganadería, el plan provincial ubica a Manabí en primer lugar nacional en carne bovina, según datos del INEC de 2019. Manta es el primer puerto pesquero del país y el primero en desembarques de atún del Pacífico suroriental.

### Sombreros, mesa y memoria

El tejido tradicional del sombrero de paja toquilla fue inscrito por la UNESCO en 2012 en la Lista Representativa del Patrimonio Cultural Inmaterial de la Humanidad. Montecristi y Jipijapa figuran entre los lugares ligados a este oficio, que también se practica en Santa Elena, Azuay, Cañar y Morona Santiago.

En Montecristi se levanta el Centro Cívico Ciudad Alfaro, un conjunto de 5,4 hectáreas con forma de cóndor. Guarda el mausoleo de Eloy Alfaro y los escaños de la Asamblea Constituyente de 2008, que sesionó allí.

La cocina local se apoya en el maní, el plátano verde y el pescado. El viche es una sopa espesa con verde, caldo de maní y pescado o marisco; la tonga lleva arroz, plátano y pollo en salsa de maní, envueltos en hoja. Entre las celebraciones, el plan provincial recoge Blancos y Negros, dedicada a San Pedro y San Pablo, que suele darse entre junio y julio.

### Fuentes

- [Gobierno Provincial de Manabí: PDOT Manabí 2030](https://www.manabi.gob.ec/wp-content/uploads/2022/09/PDOT_Manabi_2030_v1.1..pdf)
- [INEC: Censo 2022, ficha de Manabí](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Manabi.pdf)
- [CONGOPE: provincia de Manabí](https://www.congope.gob.ec/provincia-de-manabi/)
- [CONGOPE: turismo en Manabí](https://www.congope.gob.ec/turismo-manabi/)
- [Ministerio del Ambiente: áreas protegidas de la Costa](https://www.ambienteyenergia.gob.ec/wp-content/uploads/sites/2/downloads/2025/01/COSTA-3.pdf)
- [Ministerio de Educación: sombrero de paja toquilla, patrimonio de la UNESCO](https://educacion.gob.ec/cultura/ecuador-conmemora-el-decimo-aniversario-de-la-declaratoria-del-tejido-de-sombrero-de-paja-toquilla-como-patrimonio-cultural-inmaterial-de-la-humanidad/)
- [Ministerio de Educación: Centro Cívico Ciudad Alfaro](https://educacion.gob.ec/cultura/centro-civico-ciudad-alfaro-un-destino-cultural-de-manabi/)
$c$ from public.provincias where slug = 'manabi' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Pichincha, en la Sierra del Ecuador, tiene a Quito como capital y se organiza en ocho cantones: Quito, Cayambe, Mejía, Pedro Moncayo, Pedro Vicente Maldonado, Puerto Quito, Rumiñahui y San Miguel de los Bancos. Limita con Imbabura y Esmeraldas al norte, con Cotopaxi al sur, con Napo y Sucumbíos al este y con Santo Domingo de los Tsáchilas al oeste. Su superficie ronda los 9 500 km², aunque las fuentes oficiales no coinciden del todo en la cifra.

### Del páramo al subtrópico

En el centro y el este de la provincia dominan los volcanes y los valles andinos; hacia el noroccidente el terreno desciende poco a poco hacia la Costa. El volcán Cayambe llega a 5 790 m y conserva, según el Instituto Geofísico, un casquete glaciar de unos 22 km² por encima de los 4 800 m.

El clima depende de la altura. Según el Gobierno Provincial, las temperaturas medias van de unos 8 a 24 °C, desde el bosque húmedo del occidente hasta el páramo. En las lagunas de Mojanda la media ronda los 8 °C y las noches pueden bajar de los cero grados. Quito se asienta a unos 2 850 m y, según datos climáticos de referencia, sus meses más secos suelen ser de junio a septiembre.

### Ciudades y habitantes

El censo de 2022 del INEC contó 3 089 473 habitantes, lo que sitúa a Pichincha como la segunda provincia más poblada del país, detrás de Guayas. Cerca del 63 % vive en áreas urbanas. Quito reúne a 2 679 722 personas, y Rumiñahui, Cayambe y Mejía superan cada uno los 100 000. En Tababela, al este de la capital, el aeropuerto Mariscal Sucre abrió en 2013.

### Qué ver y cuándo ir

El Centro Histórico de Quito fue inscrito en la lista de Patrimonio Mundial de la UNESCO en 1978, junto con Cracovia. En él se alza la Basílica del Voto Nacional, un templo neogótico de torres de 115 m.

Fuera de la ciudad, Cochasquí conserva quince pirámides truncadas y veintiuna tolas de la cultura Quitu-Cara, a unos 52 km al norte de la capital. Las tres lagunas de Mojanda, en el límite con Imbabura, forman parte del área de conservación Mojanda-Cambugán, declarada en 2022. En el noroccidente, el Chocó Andino de Pichincha es reserva de biosfera desde 2018, y las montañas del este albergan los parques nacionales Cayambe-Coca, compartido con Imbabura, Napo y Sucumbíos, y Antisana. Al sur, en Mejía, el Refugio de Vida Silvestre Pasochoa protege un tramo de bosque andino.

El calendario festivo gira en torno a unas pocas citas. Las Fiestas de Quito se celebran alrededor del 6 de diciembre, fecha con la que tradicionalmente se recuerda la fundación de 1534. En Cayambe, las fiestas de San Pedro y el Inti Raymi suelen tener lugar a finales de junio. En Machachi, el Paseo Procesional del Chagra se realiza por lo general en julio, y en Sangolquí la Fiesta del Maíz y del Turismo llega en septiembre. Fechas y horarios se confirman en los sitios oficiales de turismo.

### Fuentes

- [Gobierno Provincial de Pichincha: información general](https://www.pichincha.gob.ec/pichincha/datos-de-la-provincia/95-informacion-general)
- [CONGOPE: provincia de Pichincha](https://www.congope.gob.ec/provincia-de-pichincha/)
- [INEC: Censo 2022, ficha de Pichincha](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Pichincha.pdf)
- [Instituto Geofísico: volcán Cayambe](https://www.igepn.edu.ec/cayambe)
- [Quito Turismo: Quito, Patrimonio Cultural de la Humanidad](https://www.quito-turismo.gob.ec/news/quito-patrimonio-cultural-de-la-humanidad/)
- [Quito Informa: Quito, Patrimonio Cultural de la Humanidad](https://www.quitoinforma.gob.ec/2023/04/18/quito-patrimonio-cultural-de-la-humanidad/)
- [Quito Informa: área protegida Mojanda-Cambugán](https://www.quitoinforma.gob.ec/2022/02/22/quito-declara-nueva-area-natural-protegida-a-27-mil-hectareas-de-mojanda-cambugan-2/)
- [Pichincha es Turismo: lagunas de Mojanda](https://pichinchaesturismo.com/es-ec/pichincha/pedro-moncayo/lagunas/lagunas-mojanda-a933b37f9)
- [Pichincha es Turismo: Parque Arqueológico Cochasquí](https://pichinchaesturismo.com/es-ec/pichincha/pedro-moncayo/zonas-arqueologicas/parque-arqueologico-cochasqui-amg8kg5fk)
- [Pichincha es Turismo: aeropuerto de Quito](https://pichinchaesturismo.com/es-ec/pichincha/quito/aeropuertos/aeropuerto-internacional-quito-aee8ab662)
- [Gobierno Provincial: Reserva de Biosfera Chocó Andino](https://www.pichincha.gob.ec/component/content/article/810-reserva-de-biosfera-del-choco-andino-de-pichincha?catid=137&Itemid=437)
- [Pichincha es Turismo: Fiesta del Maíz, Sangolquí](https://pichinchaesturismo.com/es-ec/pichincha/ruminahui/fiestas-tradicionales/fiesta-maiz-turismo-sangolqui-a771fd172)
- [Quito Informa: Fiestas de Quito](https://www.quitoinforma.gob.ec/2025/12/01/quito-en-modo-fiestas-planes-imperdibles-para-cada-dia-de-esta-semana/)
$c$ from public.provincias where slug = 'pichincha' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Santa Elena ocupa la península suroccidental de la Costa ecuatoriana, una franja de tierra baja y seca que se adentra en el Pacífico. La capital comparte el nombre y hay tres cantones: Santa Elena, La Libertad y Salinas. Al norte limita con Manabí y al este con Guayas; el océano la rodea por el oeste y el sur. Nació como provincia en 2007, un 7 de noviembre, con territorio del antiguo Guayas. Su superficie ronda los 3 700 km², aunque las fuentes oficiales no coinciden: el CONGOPE indica 3 690,17 y el Gobierno Provincial, 3 762,8.

### Un litoral seco

Sobre esta costa pesa el influjo de la fría Humboldt, que la mantiene árida, con nieblas y lloviznas débiles junto al mar. En la estación de Salinas, según datos del INAMHI, el promedio anual ronda los 23,4 °C: agosto es el mes más fresco (21,0 °C) y marzo el más cálido (26,1 °C). Llueve unos 150 mm al año, sobre todo en febrero y marzo; de junio a diciembre casi no cae agua.

En la cordillera Chongón-Colonche subsiste bosque seco y húmedo. En 2022 el Consejo Provincial aprobó un sistema de áreas de conservación y uso sostenible de 112 450 hectáreas. En el mar, según las referencias consultadas, figuran la Reserva Marina El Pelado y la reserva Puntilla de Santa Elena.

### Habitantes y economía

El censo de 2022 del INEC contó 385 735 habitantes. Santa Elena reúne a 186 687 personas, La Libertad a 112 247 y Salinas a 86 801; el 52,3 % vive en áreas urbanas.

El Gobierno Provincial menciona como sectores principales la pesca, la refinación de petróleo, el turismo, las artesanías y la hotelería de playa. Hay además puerto y el aeropuerto General Ulpiano Páez, en Salinas, inaugurado en enero de 2014 sobre la antigua base aérea. La E40 enlaza Guayaquil con Santa Elena y Salinas; su tramo hasta Salinas se entregó rehabilitado en julio de 2023. La ruta del Spondylus (E15) llega desde Manabí y se une a la E40 en la ciudad de Santa Elena.

### Qué ver y cuándo ir

Según el Gobierno Provincial, el punto más saliente de la costa continental está en La Chocolatera, en Salinas. De junio a septiembre transcurre allí la temporada de la ballena jorobada, visible incluso desde tierra. Ayangue, cerca del islote El Pelado, es comunidad de pesca y buceo; Playa Rosada tiene arena de ese color, y Montañita es balneario de surf.

La historia antigua se recorre en museos:

- Los Amantes de Sumpa, sobre un cementerio de la cultura Las Vegas, con dos jóvenes enterrados abrazados.
- El Museo Valdivia, descrito como el primer museo comunitario del país sobre un sitio arqueológico.
- El Museo Real Alto, dedicado a un poblado de casas sobre montículos en herradura.

El 7 de noviembre se recuerda la provincialización. Según fuentes no oficiales, la fiesta de Santa Elena cae el 18 de agosto y la de San Pedro el 29 de junio, y la agenda local anota el festival de cometas de Olón a finales de abril. Las fechas se confirman en sitios oficiales.

### Fuentes

- [CONGOPE: provincia de Santa Elena](https://www.congope.gob.ec/provincia-de-santa-elena/)
- [Asamblea Nacional: aniversario de la provincialización de Santa Elena](https://www.asambleanacional.gob.ec/es/blogs/maria-aquino/75448-xiv-aniversario-de-provincializacion-de-santa)
- [Gobierno Provincial de Santa Elena: información general](https://www.santaelena.gob.ec/index.php/santa-elena/23-santa-elena/santa-elena.html)
- [Gobierno Provincial de Santa Elena: balnearios](https://www.santaelena.gob.ec/index.php/balnearios)
- [Gobierno Provincial de Santa Elena: museos](https://www.santaelena.gob.ec/index.php/museos)
- [INEC: Censo 2022, ficha de Santa Elena](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Santa_Elena.pdf)
- [IGM: clima e hidrología de Santa Elena](https://www.geoportaligm.gob.ec/geodescargas/santa_elena/mt_santa_elena_clima_e_hidrologia.pdf)
- [Presidencia: vías en Santa Elena, julio de 2023](https://www.presidencia.gob.ec/wp-content/uploads/downloads/2023/07/2023.07.12-VIAS-EN-SANTA-ELENA.pdf)
- [MIT: inauguración del aeropuerto de Salinas](https://www.mit.gob.ec/aeropuerto-de-salinas-se-inauguro-con-el-anuncio-de-proximas-rutas-comerciales/)
- [Ministerio del Ambiente: ballenas jorobadas en Santa Elena](https://www.ambienteyenergia.gob.ec/ambiente/primer-avistamiento-de-ballenas-jorobadas-en-las-costas-de-santa-elena/)
- [El Universal: sistema provincial de áreas protegidas de Santa Elena](https://www.eluniverso.com/larevista/ecologia/santa-elena-creo-un-sistema-provincial-de-areas-protegidas-para-conservar-112450-hectareas-de-bosque-seco-y-humedo-nota/)
- [Ministerio de Educación: museo Amantes de Sumpa](https://educacion.gob.ec/cultura/el-museo-amantes-de-sumpa-abrira-sus-puertas-este-primero-de-mayo/)
$c$ from public.provincias where slug = 'santa-elena' on conflict (provincia_id) do nothing;
