-- Generated by scripts/generate-content-migration.ts from content/provincias/*.md.
-- Do not edit by hand: regenerate with `pnpm content:seed-sql`.
-- `on conflict do nothing` is deliberate: re-running never overwrites edits made from the UI.

insert into public.provincia_contenido (provincia_id, body) select id, $c$Antes de llamarse Azuay, estas tierras fueron Guapondelig, territorio cañari, y luego Tomebamba, la ciudad inca. Sobre sus restos fundó Gil Ramírez Dávalos, en abril de 1557 la actual Cuenca, capital provincial. La provincia se creó en junio de 1824 como departamento que reunía a Cuenca, Loja y Jaén, y con los años quedó reducida a unos 8 300 km² y quince cantones. Limita con Cañar al norte, con Loja al sur, con Morona Santiago y Zamora Chinchipe al este, y con Guayas y El Oro hacia el occidente.

### Una historia de capas

Los cañaris resistieron a Túpac Yupanqui hacia 1460 y fueron vencidos; Chordeleg y Sígsig habían sido centros de poder de su élite. En Guapondelig los incas levantaron palacios, templos y baños cuyos vestigios se ven hoy en el museo Pumapungo. Cuenca proclamó su independencia en noviembre de 1820 y Sucre la consolidó en 1822. Loja se separó en 1835 y Azogues, que dio origen a Cañar como provincia, en 1880.

### Páramos, agua y energía

Azuay está en el sur de la región interandina, entre las cordilleras Occidental y Oriental, con sus ciudades principales asentadas en valles. En el nudo de El Cajas, de unos 4 500 m, nace buena parte del agua provincial. El Parque Nacional Cajas tiene 28 544 ha y, junto con otras 845 al norte, forma un humedal Ramsar desde 2002. Es zona núcleo de la Reserva de Biósfera Macizo del Cajas (UNESCO, 2010), que cubre 535 000 ha de la provincia, el 64,5 % de su superficie. El páramo ocupa casi una cuarta parte del territorio.

Llueve sobre todo de diciembre a mayo; de junio a noviembre es la época más seca. El río Paute modela el nororiente provincial. La central Paute Molino, conocida como Cola de San Pablo, tiene 1 100 MW, es la segunda hidroeléctrica del país según CELEC y opera desde 1983.

### Gente y economía

El censo de 2022 contó 801 609 habitantes, el 52,4 % en zonas urbanas. Cuenca concentra 596 101. Hay 61 parroquias rurales y 15 urbanas. Los servicios dominan la economía; la agricultura aporta el 2,60 % del valor agregado. En 2022 la encuesta agropecuaria destacó por superficie el maíz duro seco, la papa, el banano y la caña, y el hato sumaba 286 315 vacunos, el 7,4 % nacional.

En el oeste, 819 concesiones mineras abarcan unas 224 963 ha, casi un cuarto del territorio. En Camilo Ponce Enríquez la minería es el principal sector por valor agregado, y gran parte de las concesiones se superpone con páramos y zonas de recarga hídrica.

### Oficios y mesa

Con denominación de origen, los sombreros tejidos en paja toquilla proceden sobre todo de Cuenca, Gualaceo, Chordeleg y Sígsig. Chordeleg es famosa por su joyería de filigrana y Gualaceo por sus textiles. En Cuenca, la Catedral Nueva, el Parque Calderón y los museos concentran la visita. En la mesa figuran el cuy asado, el tamal, el mote pata y el caldo de pata, plato de Carnaval hecho con maíz y habas.

### Fuentes

- [Gobierno Provincial del Azuay: PDOT 2024-2030](https://www.azuay.gob.ec/wp-content/uploads/2026/07/PLAN-DE-DESARROLLO-Y-ORDENAMIENTO-TERRITORIAL-DE-LA-PROVINCIA-DEL-AZUAY-2024-2030.pdf)
- [INEC: Censo 2022, ficha de Azuay](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_azuay.pdf)
- [CONGOPE: provincia de Azuay](https://www.congope.gob.ec/provincia-de-azuay/)
- [CONGOPE: turismo en Azuay](https://www.congope.gob.ec/turismo-azuay/)
- [CELEC: central hidroeléctrica Paute Molino](https://www.celec.gob.ec/hidropaute/central-hidroelectrica-paute-molino/)
$c$ from public.provincias where slug = 'azuay' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Bolívar es una provincia de relieve quebrado y pocas llanuras, donde en pocos kilómetros se pasa del páramo helado a valles cálidos que miran hacia la Costa. Su capital es Guaranda, y la integran siete cantones: Guaranda, Chillanes, San Miguel, Chimbo, Echeandía, Caluma y Las Naves. Según la Prefectura y el CONGOPE, tiene 3 945 km². La Prefectura la cuenta como la décima cuarta provincia del país, creada en abril de 1884.

### Un territorio de contrastes

Bolívar se sitúa en el corazón del Ecuador, en la hoya del Chimbo y sobre el flanco exterior de la cordillera Occidental. Colinda con Cotopaxi al norte, con Guayas al sur y con Los Ríos al oeste; al este, solo con Chimborazo. Según el plan de desarrollo provincial, su relieve va del páramo, desde unos 3 500 m, hasta alturas de 4 680 m, y las temperaturas oscilan entre -1 y 26 °C.
Toda el agua de la provincia corre hacia la cuenca del Guayas. El río Chimbo nace de la unión del Guaranda y el Salinas, sirve de límite natural con Chimborazo y, ya en la Costa, contribuye a formar el Yaguachi. El área protegida Chimborazo, creada en 1987 para conservar su fauna, también entra en territorio bolivarense: son 13 546 ha de las 58 560 que registra el plan.

### Gente y sustento

El censo de 2022 contó 199 078 habitantes, de los cuales el 67,8 % vive en el campo, lo que la hace una de las provincias más rurales. Guaranda reúne 98 130 personas, casi la mitad del total. El 68,6 % se identificó como mestizo y el 29,5 % como indígena.

Por superficie sembrada predominan el maíz suave, con 32 000 ha, seguido del cacao, con 18 000, y la naranja, con 11 200, según cifras agrícolas de 2018 recogidas en el plan provincial.

### Historia

La Prefectura recuerda que estas tierras estuvieron habitadas por los puruháes antes de la conquista inca. El camino entre Quito y Guayaquil, que pasaba por Guaranda, impulsó su desarrollo colonial. En 1820, tras el triunfo patriota de Camino Real, el 9 de noviembre, la independencia se proclamó en Guaranda al día siguiente. Después, el territorio perteneció a Chimborazo y a Los Ríos hasta alcanzar su condición de provincia en 1884.

### Qué ver

Guaranda se conoce como la ciudad de las siete colinas. Está a 2 668 m de altitud y ofrece vistas del Chimborazo. Su Carnaval es la máxima expresión cultural de la provincia, y fue declarado Patrimonio Cultural Intangible de la Nación el 31 de octubre de 2002.

El plan provincial destaca varias rutas: el Camino de la Sal, los Hieleros del Chimborazo, el Camino Real y el Camino de los Santos, que enlaza santuarios como el de la Virgen del Huayco y el del Señor de la Salud. Para quien busque aventura, están los senderos de Las Cochas, en Guaranda, y la cascada de La Chorrera, en Caluma.

### Fuentes

- [Gobierno Provincial de Bolívar: PDOT 2015-2020](https://www.bolivar.gob.ec/wp-content/uploads/2020/07/PDOT.pdf)
- [Gobierno Provincial de Bolívar: historia](https://www.bolivar.gob.ec/historia/)
- [INEC: Censo 2022, ficha de Bolívar](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Bolivar.pdf)
- [CONGOPE: provincia de Bolívar](https://www.congope.gob.ec/provincia-de-bolivar/)
- [Municipio de Guaranda: datos importantes](https://www.guaranda.gob.ec/newsiteCMT/datos-importantes/)
$c$ from public.provincias where slug = 'bolivar' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Antes de llamarse Cañar, esta provincia se llamó Azogues. El Congreso la erigió el 3 de noviembre de 1880 con los cantones Azogues y Cañar y la parroquia Déleg, y el 3 de noviembre de 1884 adoptó su nombre actual. Hoy tiene siete cantones (Azogues, Biblián, Cañar, Déleg, El Tambo, La Troncal y Suscal), 33 parroquias, 7 urbanas y 26 rurales, y su capital sigue siendo Azogues. Su superficie depende de la fuente: va de unos 3 200 a unos 4 100 km², y las zonas en disputa con provincias vecinas mantienen abierta la cifra.

### Un territorio de altura que baja hasta la costa

Cañar limita con Chimborazo al norte, con Azuay al sur, con Guayas al oeste y con Morona Santiago al este. Su núcleo es la hoya del Cañar, cerrada por el nudo del Azuay y por montañas que la separan de los valles vecinos. La altitud pasa de 17 m en el extremo occidental a 4 637 m en el norte, dentro del Parque Nacional Sangay, del que unas 98 255 ha pertenecen a la provincia. En ese parque se cuenta la laguna de Culebrillas, cabecera del río Cañar, que nace en los páramos de Quinaloma y desciende hacia el Pacífico.

El clima sigue la altura. En Azogues, Biblián y Déleg las medias mensuales oscilan entre 8,3 y 17,4 °C, mientras La Troncal, en tierras bajas, es cálida. En el oriente, el Mazar y el Dudas alimentan el Paute, y sobre el Dudas funciona la central hidroeléctrica Mazar-Dudas, en la parroquia Rivera.

### Gente y producción

El censo de 2022 contó 227 578 habitantes, el 44,4 % en áreas urbanas. Azogues reúne a 74 515 personas, La Troncal a 62 103 y Cañar a 52 150. El 82,7 % se identificó como mestizo y el 14,7 % como indígena; más de 32 000 personas se reconocieron cañaris o kichwas, sobre todo en Suscal, El Tambo, Cañar y Biblián.

En la sierra se cultivan maíz, papa, fréjol, trigo y cebada, y la ganadería tiene peso. En La Troncal, en cambio, prosperan el arroz, el cacao y la caña de azúcar. Azogues y Biblián tienen concesiones de caolín y caliza, y se tejen sombreros de paja toquilla.

### Memoria cañari e inca

Los arqueólogos distinguen tres fases de la cultura cañari: Tacalshapa, Narrío y Cashaloma, entre el 500 a. C. y 1460 d. C. La última, en Ingapirca, marca el tránsito al dominio inca. Ingapirca es el sitio arqueológico más grande y mejor conservado del país; otro asentamiento monumental, Cojitambo, se levanta en el cantón Azogues. Tramos del Qhapaq Ñan cruzan la provincia, y el conjunto fue inscrito por la UNESCO en 2014. En 2001 el cantón Cañar fue declarado Capital Arqueológica y Cultural del Ecuador.

### Fiestas

El calendario mezcla lo ancestral y lo católico. En febrero y marzo, el Pawkar Raymi coincide con el carnaval y con el Tayta Carnaval, que recorre las casas. El 8 de septiembre Biblián celebra a la Virgen del Rocío, y el 1 de enero Azogues realiza la procesión de la Virgen de la Nube.

### Fuentes

- [Gobierno Provincial del Cañar: PDOT 2023-2027](https://www.gobiernodelcanar.gob.ec/wp-content/uploads/2025/02/PDOT-2023-2027.pdf)
- [INEC: Censo 2022, ficha de Cañar](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Canar.pdf)
- [Gobierno Provincial del Cañar: la provincia](https://www.gobiernodelcanar.gob.ec/la-provincia-del-canar/)
- [Gobierno Provincial del Cañar: cantón Cañar](https://www.gobiernodelcanar.gob.ec/canton-canar/)
- [Gobierno Provincial del Cañar: cantón Azogues](https://www.gobiernodelcanar.gob.ec/canton-azogues/)
- [CONGOPE: provincia de Cañar](https://www.congope.gob.ec/provincia-de-canar/)
$c$ from public.provincias where slug = 'canar' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Carchi cierra el país por el norte: al norte limita con Colombia y al sur con Imbabura. Su capital es Tulcán y se divide en seis cantones: Tulcán, Bolívar, Espejo, Mira, Montúfar y San Pedro de Huaca, uno por cada estrella de su bandera. Según el CONGOPE, ocupa 3 780,45 km². La Prefectura fecha su provincialización el 19 de noviembre de 1880, día en que se celebra la fiesta cívica.

### Páramos y volcanes

El territorio es andino y de clima muy variado, desde valles cálidos hasta páramos helados. En la frontera se alzan los volcanes Chiles, de 4 748 m, y Cerro Negro, de 4 470 m, a unos 25 km al oeste de Tulcán. El Instituto Geofísico los considera potencialmente activos: registra actividad hidrotermal y una sismicidad elevada desde 2013, con sismos de magnitud 5,6 en 2014 y 2022, aunque no se les conocen erupciones históricas confirmadas.

En el cantón Espejo está la Reserva Ecológica El Ángel, un páramo de frailejones y bosques de polylepis. En San Pedro de Huaca se encuentra la Reserva Biológica Guanderas.

### Gente y economía

El censo de 2022 contó 172 828 habitantes, el 50,9 % en zonas urbanas. Tulcán reúne a 92 375 y Montúfar a 29 590. El 89,6 % se identificó como mestizo, el 5,2 % como afroecuatoriano y el 4,2 % como indígena. La Prefectura atribuye el origen del poblamiento a los pueblos pastos y destaca la fuerte tradición afroecuatoriana de Mira.

La agricultura, la ganadería, el comercio y el turismo sostienen la economía. San Pedro de Huaca figura entre los grandes productores de papa del país, y la cercanía de la frontera da al comercio un peso propio. Las precipitaciones de referencia publicadas por la Prefectura rondan los 900 mm anuales en Tulcán y los 1 000 mm en San Gabriel.

### Qué ver

En Tulcán, el cementerio funciona como museo al aire libre: sus jardines están esculpidos en ciprés. A la salida de la ciudad, el puente binacional de Rumichaca sobre el río Carchi marca el paso hacia Colombia. Entre los atractivos naturales constan las Lagunas Verdes, las cascadas de Paluz, La Bretaña, El Pailón y Tuscuaza, varias aguas termales y el valle del Chota.

Mira, llamada el Balcón de los Andes, está a unos 92 km al sur de Tulcán, a 2 100 m de altura y con una temperatura media de 16 grados. Su municipio celebra a la Virgen de la Caridad el 28 de enero. San Gabriel, en Montúfar, se presenta como la Ciudad de la Eterna Primavera. La Prefectura también asocia la provincia con el ciclista Richard Carapaz.

### Mesa carchense

La oferta gastronómica incluye cuy asado, hornado y caldo de gallina, platos de la sierra norte que se encuentran en los restaurantes de la provincia.

Una advertencia útil: el Santuario de Las Lajas, que algunos listados turísticos asocian a la zona, queda en Ipiales, Colombia, no en Carchi.

### Fuentes

- [CONGOPE: Provincia de Carchi](https://www.congope.gob.ec/provincia-de-carchi/)
- [CONGOPE: Turismo en Carchi](https://www.congope.gob.ec/turismo-carchi/)
- [Prefectura de Carchi: nuestra provincia](https://carchi.gob.ec/web/nuestra-provincia/)
- [Prefectura de Carchi: símbolos provinciales](https://carchi.gob.ec/web/simbolos-provinciales/)
- [INEC: Censo 2022, ficha de Carchi](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Carchi.pdf)
- [Instituto Geofísico: Chiles y Cerro Negro](https://www.igepn.edu.ec/chiles-cerro-negro)
$c$ from public.provincias where slug = 'carchi' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Quien llega a Chimborazo lo primero que busca con la vista es el nevado que le da nombre: 6 263 m de altura según el Instituto Geofísico, que lo describe como el volcán más alto del norte de los Andes. Es un volcán potencialmente activo, con casquete glaciar; su última erupción ocurrió entre los siglos V y VII y hoy solo muestra actividad hidrotermal. Riobamba es la capital de una provincia de 6 578,10 km², según su plan de desarrollo, cuyo relieve baja hasta unos 135 m y sube hasta los 6 310 m.

### Un territorio de cuencas y fronteras

El agua organiza el mapa. Más de la mitad del territorio, el 53,72 %, drena al sistema del Pastaza, por el río Chambo hacia la Amazonía; otro 36,58 % pertenece al del Guayas, con el Chanchán rumbo al Pacífico. Al sur limita con Cañar, al este con Morona Santiago y al oeste con Bolívar y Guayas. Con Cañar y con Guayas, además, mantiene diferendos de límites: el plan provincial registra dos con Cañar y el del sector La Isla, en Cumandá, con Guayas.

### Páramos protegidos

Cerca del 17,6 % de la provincia está bajo conservación. El Parque Nacional Sangay aporta 80 859 ha, con Los Cubillines, el macizo del Altar y un complejo de 19 lagunas. El volcán Sangay, en cambio, queda en Morona Santiago. La Reserva de Producción de Fauna Chimborazo suma otras 11 791 ha dentro de la provincia y protege al Chimborazo y al Carihuayrazo, hogar de llamas, vicuñas y alpacas.

### Gente e historia

El censo de 2022 contó 471 933 habitantes, de los cuales el 52,4 % vive en el campo: aquí lo rural pesa más que lo urbano. Un 60,7 % se identificó como mestizo y un 37,9 % como indígena; el pueblo puruwá, con subgrupos como cachas y coltas, habita estas tierras desde antes de la conquista. Los primeros asentamientos, de unos 5 000 años, aparecen cerca de Punín, donde también se halló un mastodonte que dio fama al sitio paleontológico.

La colonización española comenzó en agosto de 1534 con la fundación de Santiago de Quito, antecesora del corregimiento de Riobamba. La provincia nació de un decreto de división política firmado en junio de 1824. Hoy la forman diez cantones y 61 parroquias, dieciséis urbanas y cuarenta y cinco rurales. Riobamba concentra 260 882 personas.

### Trabajo y caminos

Los servicios generan el 72,36 % del valor agregado provincial. La industria es escasa y destacan una cementera y una fábrica de cerámica; también hay minería, sobre todo en Riobamba y Alausí, y hay centrales hidroeléctricas. La Troncal de la Sierra cruza el territorio, y la vía Riobamba-Guamote-Macas abre paso a la Amazonía.

### Para recorrerla

El turismo ferroviario se concentra en el tramo de Alausí a Sibambe, la ruta de la Nariz del Diablo. Alausí guarda además 71 sitios arqueológicos y tramos del Qhapaq Ñan. Entre los atractivos naturales figuran la laguna de Colta, los lagos de Ozogoche y Atillo y varias cascadas, como la Chorrera del Diablo y Paila de Oro.

### Fuentes

- [GAD Provincial de Chimborazo: PDOT 2020-2023](https://chimborazo.gob.ec/principal/wp-content/uploads/2022/06/PDOT.pdf)
- [INEC: Censo 2022, ficha de Chimborazo](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Chimborazo.pdf)
- [Instituto Geofísico: volcán Chimborazo](https://www.igepn.edu.ec/chimborazo)
- [Instituto Geofísico: volcán Sangay](https://www.igepn.edu.ec/sangay)
$c$ from public.provincias where slug = 'chimborazo' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Cotopaxi ocupa la parte media del callejón andino y tiene a Latacunga como capital. Ocupa unos 6 108,23 km², según el CONGOPE, y se organiza en siete cantones: La Maná, Latacunga, Pangua, Pujilí, Salcedo, Saquisilí y Sigchos. El censo de 2022 contó 470 210 habitantes, de los cuales dos de cada tres viven en el campo.

### Montañas y lagunas

Dos cordilleras enmarcan el territorio. Al oriente domina el volcán Cotopaxi, de 5 897 m, que el Instituto Geofísico ubica a unos 35 km al noreste de Latacunga. Su historia pesa en la región: el instituto registra cinco periodos eruptivos desde la llegada de los españoles, el último de ellos entre 1877 y 1880, y advierte que los lahares amenazarían a más de 300 000 personas.

Hacia el occidente se encuentra el Quilotoa, una caldera ocupada por una laguna. Mide 3 914 m, su cráter tiene cerca de 2 km y su última erupción ocurrió hace unos 800 años, por lo que se le considera potencialmente activo. Latacunga, por su parte, recorre una gran escala de alturas: desde los 1 800 m hasta la cumbre del Cotopaxi.

### Áreas protegidas

La provincia reúne varias figuras de conservación. El Parque Nacional Cotopaxi incluye la laguna de Limpiopungo, a más de 3 400 m de altitud. La Reserva Ecológica Los Ilinizas, en la cordillera Occidental, abarca terrenos de los cantones Latacunga, La Maná, Pujilí, Sigchos y Pangua, además de áreas de Pichincha y de Santo Domingo de los Tsáchilas. El Parque Nacional Llanganates se reparte entre cuatro provincias: Cotopaxi, Tungurahua, Pastaza y Napo. A ellos se suma el Área Nacional de Recreación El Boliche.

### Gente y cantones

Según el censo de 2022, el 73,5 % de la población se identificó como mestiza y el 23,7 % como indígena; la mediana de edad fue de 28 años. Latacunga concentra a 217 261 personas, seguida por Salcedo con 67 493, Pujilí con 66 980 y La Maná con 53 793.

Cada cantón tiene su propio carácter. Latacunga es el centro administrativo y comercial, con parroquias que van de la sierra al subtrópico. Pujilí conserva una fuerte herencia indígena y es conocido por su cerámica y sus textiles. Saquisilí se identifica con su feria multicolor. Salcedo, a 2 683 m, es famoso por sus helados. Sigchos recibe el apodo de «Jardín Colgante de los Andes», Pangua funciona como zona de transición con centro en El Corazón, y La Maná, de clima subtropical, está ligado al banano, el cacao y el café.

### Fiestas

La Mama Negra es la celebración más conocida de Latacunga. Tiene dos versiones: una religiosa, hacia el 23 y 24 de septiembre, y otra cívica en noviembre, que recuerda la independencia de la ciudad y suele tener su día principal el primer sábado del mes.

### Fuentes

- [CONGOPE: Provincia de Cotopaxi](https://www.congope.gob.ec/provincia-de-cotopaxi/)
- [INEC: Censo 2022, ficha de Cotopaxi](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Cotopaxi.pdf)
- [Instituto Geofísico: volcán Cotopaxi](https://www.igepn.edu.ec/cotopaxi)
- [Instituto Geofísico: volcán Quilotoa](https://www.igepn.edu.ec/quilotoa)
- [Gobierno Provincial de Cotopaxi: cantones](https://cotopaxi.gob.ec/cantones-provincia/)
- [Secretaría de Gestión de Riesgos: Reserva Ecológica Los Ilinizas](https://www.gestionderiesgos.gob.ec/reserva-ecologica-los-illinizas-cuenta-con-un-plan-integral-de-gestion-de-riesgos/)
$c$ from public.provincias where slug = 'cotopaxi' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$El Oro ocupa el suroeste de la Costa ecuatoriana, donde la llanura frente al Pacífico da paso a los primeros relieves andinos. Su capital es Machala, que el plan provincial llama «Capital Bananera del Mundo». Fue provincializada en 1884, el 23 de abril, y hoy reúne 14 cantones. Su superficie ronda los 5 800 km², aunque las cifras oficiales difieren un poco entre sí. Limita con Guayas y Azuay al norte, con Loja al sur y al este y con el Pacífico al oeste; además comparte frontera con Perú.

### De los manglares a los 3 900 metros

En pocos kilómetros el terreno sube del nivel del mar a unos 3 900 m. Según el INABIO, es el punto donde los Andes se aproximan más al océano. La costa noroccidental, entre 0 y 50 m, ocupa cerca del 38 % del territorio; el resto son faldas occidentales que llegan a 3 590 m en el cerro Chilla-Cocha.

El plan provincial describe una costa de verano seco e invierno lluvioso, con 20 a 26 °C, y una zona alta más lluviosa, de 10 a 18 °C.

En Arenillas y Huaquillas, una reserva ecológica protege bosque seco tumbesino; el INABIO le atribuye 13 170 ha. En el límite con Loja está Puyango, bosque protector desde 1987 y patrimonio cultural nacional desde 1988, con 2 659 ha de troncos fósiles de unos 100 millones de años.

### Banano, camarón y oro

El censo de 2022 contó 714 592 habitantes, cerca del 78 % en áreas urbanas. Machala suma 306 309, y le siguen Pasaje, Santa Rosa, El Guabo y Huaquillas.

El banano es la actividad más significativa: según la prefectura, equivale a cerca del 30 % de la economía provincial, y su auge arrancó en la década de 1940. También pesan el cacao, el café y el camarón; El Oro es la segunda provincia del país en este último rubro, que empezó en 1966. Puerto Bolívar, junto a Machala, es el segundo puerto marítimo después del de Guayaquil. En Zaruma y Portovelo sigue la minería de oro, y el comercio se apoya en la frontera con Perú.

### Qué ver y cuándo son las fiestas

Frente a la costa se extiende el archipiélago de Jambelí, con manglar y playa, a unos 30 minutos en lancha desde Puerto Bolívar o Puerto Hualtaco. Más lejos queda la isla Santa Clara, refugio de aves marinas y lobos marinos; la guía oficial de turismo sitúa allí la temporada de ballenas entre agosto y octubre.

Zaruma, en la parte alta, fue declarada Patrimonio Cultural del Estado en 1990 y consta desde 1998 en la lista indicativa de la UNESCO. Celebra en julio las fiestas de la Virgen del Carmen; el programa de 2025 iba del 4 al 27.

En septiembre Machala organiza la Feria Mundial del Banano, que según medios locales forma parte de las fiestas de la Virgen de la Merced; su 61.ª edición se anunció para el 17 al 20 de septiembre de 2026. Machala se atiende desde el Aeropuerto Regional de Santa Rosa, operativo desde 2008.

### Fuentes

- [Gobierno Provincial de El Oro: PDYOT 2024-2027](https://datos.eloro.gob.ec/PDF%20PDYOT/PDYOT%20-%202024%20-%202027.pdf)
- [INEC: Censo 2022, ficha de El Oro](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_El-Oro.pdf)
- [CONGOPE: provincia de El Oro](https://www.congope.gob.ec/provincia-de-el-oro/)
- [INABIO y GAD de El Oro: propuesta de corredor ecológico, 2019](http://inabio.biodiversidad.gob.ec/wp-content/uploads/2020/10/Libro%20Propuesta%20ACP%20y%20Corredor%20Ecol%C3%B3gico%20de%20la%20provincia%20de%20El%20Oro%202019.pdf)
- [El Universo: fósiles de Puyango](https://www.eluniverso.com/noticias/2019/12/06/nota/7637105/bosque-petrificado-puyango-historia-oro-fosiles-loja/)
- [El Universo: Zaruma, riqueza cultural](https://www.eluniverso.com/noticias/2020/11/25/nota/8061649/riqueza-cultural-destaca-bicentenaria-zaruma/)
- [Ecuador Travel: turismo en Santa Rosa, El Oro](https://ecuador.travel/turismo-en-santa-rosa-el-oro/)
- [Municipio de Zaruma: programa de festividades 2025](https://www.zaruma.gob.ec/assets/18_PROGRAMA.%20DE%20FESTIVIDADES%202025.pdf)
- [Machala Móvil: 61.ª Feria Mundial del Banano](https://machalamovil.com/prefecta-karina-torres-inaugura-este-jueves-la-edicion-61-de-la-feria-mundial-del-banano/)
$c$ from public.provincias where slug = 'el-oro' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Esmeraldas ocupa el extremo noroccidental del Ecuador, donde el país toca el Pacífico y la frontera con Colombia. Su capital es la ciudad de Esmeraldas y se divide en siete cantones: Esmeraldas, Atacames, Eloy Alfaro, Muisne, Quinindé, Ríoverde y San Lorenzo. Al este colinda con Carchi e Imbabura, hacia el sureste con Pichincha, y al sur con Manabí y Santo Domingo de los Tsáchilas. Su superficie ronda los 15 800 km², aunque las cifras oficiales difieren un poco.

### Una población afroecuatoriana y diversa

El censo de 2022 del INEC contó 553 900 habitantes, algo más de la mitad en el campo (55,1 %). El cantón Esmeraldas reúne a 211 848 personas y Quinindé, el segundo en tamaño, a 126 841. Más de la mitad de los habitantes, el 53,8 %, se identificó como afroecuatoriana; el 39,5 % como mestiza y el 3,4 % como indígena.

Esa mezcla se refleja en la música. La marimba, unida a los cantos y bailes tradicionales del Pacífico sur colombiano y esmeraldeño, figura desde 2015 en la Lista Representativa del Patrimonio Cultural Inmaterial de la UNESCO. El Museo y Centro Cultural Esmeraldas, abierto en 1979, documenta las culturas afroesmeraldeña, chachi, awá y épera, además de piezas arqueológicas tolitas, teaone y atacameñas.

### Manglares y bosques protegidos

En el norte, la Reserva Ecológica Manglares Cayapas-Mataje protege el estuario de los dos ríos que le dan nombre, en los cantones San Lorenzo y Eloy Alfaro. La guía de visitantes del Ministerio del Ambiente, publicada en 2024, señala que sus manglares alcanzan hasta 60 m de altura, y los describe como los más altos del mundo. Las salidas a observar aves o delfines dependen de la marea.

Más al sur, la Reserva Ecológica Mache Chindul resguarda bosques húmedos y secos de la cordillera del mismo nombre, con la laguna de Cube y la cascada Colorado como puntos de referencia; el acceso parte de Quinindé. Hacia el este, la provincia comparte con Imbabura el Parque Nacional Cotacachi-Cayapas.

### Playas, mesa y fechas

La costa reúne balnearios de carácter distinto. Atacames es la playa más concurrida y tiene malecón con restaurantes; Tonsupa resulta más tranquila y familiar; Mompiche es un pueblo pesquero con olas apreciadas por quienes practican surf, y Súa, una aldea pesquera. En la mesa abundan el encocado, el arroz con concha, la cazuela de mariscos y la tonga, preparada con salsa de maní y cocida dentro de una hoja de plátano.

El 5 de agosto se conmemora la independencia de Esmeraldas, con desfile cívico-militar y sesión solemne; en 2025 se cumplieron 205 años. En noviembre la Prefectura recuerda la provincialización, que fija el 20 de noviembre de 1847 como fecha oficial.

### Cómo llegar

Desde Quito hay dos rutas por la vía E20: una por Calacalí y La Independencia, y otra por Santo Domingo. En Tachina, junto a la capital provincial, se encuentra el aeropuerto Carlos Concha Torres; su servicio comercial ha sido intermitente y la Dirección General de Aviación Civil es la fuente para saber si hay vuelos.

### Fuentes

- [CONGOPE: provincia de Esmeraldas](https://www.congope.gob.ec/provincia-de-esmeraldas/)
- [Prefectura de Esmeraldas: la provincia](https://prefecturadeesmeraldas.gob.ec/index.php/provincia-de-esmeraldas/)
- [Prefectura de Esmeraldas: provincialización](https://www.prefecturadeesmeraldas.gob.ec/web/assets/provincializacion.pdf)
- [INEC: Censo 2022, ficha de Esmeraldas](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Esmeraldas.pdf)
- [Gobierno Provincial de Pichincha: información general](https://www.pichincha.gob.ec/pichincha/datos-de-la-provincia/95-informacion-general)
- [UNESCO: marimba, cantos y bailes tradicionales](https://ich.unesco.org/en/RL/marimba-music-traditional-chants-and-dances-from-the-colombia-south-pacific-region-and-esmeraldas-province-of-ecuador-01099)
- [Ministerio del Ambiente: guía de visitantes de la Costa, 2024](https://www.ambienteyenergia.gob.ec/wp-content/uploads/sites/2/downloads/2024/11/COSTA-1-OK.pdf)
- [Museo y Centro Cultural Esmeraldas](https://educacion.gob.ec/cultura/museo-y-centro-cultural-esmeraldas/)
- [Ecuador Travel: Esmeraldas](https://ecuador.travel/esmeraldas-donde-la-naturaleza-y-la-cultura-afroecuatoriana-te-esperan/)
- [AME: fiestas de independencia de Esmeraldas](https://ame.gob.ec/esmeraldas-celebra-a-lo-grande-sus-fiestas-de-independencia/)
- [DGAC: vuelos en el aeropuerto Carlos Concha Torres](https://www.aviacioncivil.gob.ec/se-retoman-vuelos-desde-el-aeropuerto-carlos-concha-torres-de-esmeraldas/)
- [Ministerio del Ambiente: Parque Nacional Cotacachi-Cayapas](https://www.ambienteyenergia.gob.ec/ambiente/el-parque-nacional-cotacachi-cayapas-conmemoro-sus-53-anos-de-creacion/)
$c$ from public.provincias where slug = 'esmeraldas' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$En 1535 un obispo, fray Tomás de Berlanga, llegó a estas islas sin proponérselo, y así las conoció el mundo hispano. Casi cuatro siglos y medio después, en 1973, el archipiélago pasó a ser la provincia de Galápagos, cuya capital es Puerto Baquerizo Moreno, en San Cristóbal. Se divide en tres cantones, San Cristóbal, Isabela y Santa Cruz, y tiene cinco parroquias rurales.

### Un archipiélago en medio del Pacífico

Las islas quedan al oeste del continente, sobre la línea ecuatorial. La UNESCO calcula unos 1 000 km hasta la costa ecuatoriana y el Instituto Geofísico precisa 972 km. El recuento de islas cambia según la fuente: el Instituto Geofísico y el Plan de Manejo hablan de 13 islas grandes, mientras que la Agenda Zonal enumera 19 islas, 47 islotes y al menos 26 rocas.

La tierra emergida suma unos 7 970 km². De ellos, 7 610 km², el 96,7 %, pertenecen al Parque Nacional, y los 260 km² restantes son zona colonizada, urbana y agrícola. Isabela sola reúne 4 703 km², el 59 % de la superficie insular.

### Fuego bajo el mar

Todo el archipiélago es de origen volcánico, y en su base chocan las placas de Nazca, Cocos y Pacífico. Isabela y Fernandina son las más jóvenes, con menos de un millón de años, y Española y San Cristóbal las más antiguas, entre tres y cinco millones. El Instituto Geofísico cuenta unas sesenta erupciones en tiempos históricos, casi siempre de lava basáltica.

El Wolf, en el norte de Isabela, mide 1 707 m y es la cima más alta del archipiélago; la línea ecuatorial pasa por el volcán. Otro gigante de Isabela es el Alcedo, de caldera amplia. En 2020 entró en erupción el Fernandina, y los guardaparques observaron el proceso desde la estación del Canal Bolívar.

### Gente y oficios

El censo de 2022 registró 28 583 habitantes, el 79,6 % en zonas urbanas. Santa Cruz concentra 17 233 personas, San Cristóbal 8 300 e Isabela 3 050. Sus poblados principales son Puerto Ayora, Puerto Baquerizo Moreno y Puerto Villamil.

La ocupación humana fue lenta. Isabela albergó una colonia penal entre 1946 y 1959, y el turismo se asomó desde los años treinta, con una explosión hacia fines de los sesenta. Desde 1992 la pesca del pepino de mar vivió un auge y, una década más tarde, ya estaba sobreexplotada. Hoy el turismo y los servicios sostienen la economía.

### Protección y ciencia

El Parque Nacional se declaró en 1959, fue la primera área protegida del país y en 1978 la UNESCO lo incluyó en su lista del patrimonio mundial, como bien natural. La Reserva Marina nació en 1998 con una franja de 40 millas náuticas y unos 138 000 km². Ese mismo año de 1959 se creó la Fundación Charles Darwin, cuya Estación Científica abrió en Puerto Ayora en 1964.

La UNESCO destaca iguanas marinas, cormoranes no voladores, cactus gigantes y sinsontes, además de los pinzones y las tortugas gigantes que inspiraron a Darwin, quien visitó las islas en 1835.

### Fuentes

- [INEC: Censo 2022, ficha de Galápagos](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Galapagos.pdf)
- [Dirección del Parque Nacional Galápagos: Plan de Manejo 2014](https://www.galapagos.gob.ec/wp-content/uploads/downloads/2016/07/DPNG_Plan_de_Manejo_2014.pdf)
- [UNESCO: Islas Galápagos](https://whc.unesco.org/en/list/1)
- [Instituto Geofísico: islas Galápagos](https://www.igepn.edu.ec/islas-galapagos)
- [SENPLADES: Agenda Zonal de Galápagos](https://www.gobiernogalapagos.gob.ec/wp-content/uploads/downloads/2013/08/AGENDA-ZONAL_GALAPAGOS_SENPLADES.pdf)
- [Parque Nacional Galápagos: 61 años como primera área protegida](https://galapagos.gob.ec/el-parque-nacional-galapagos-celebra-sus-61-anos-como-la-primera-area-protegida-del-pais/)
$c$ from public.provincias where slug = 'galapagos' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Guayas ocupa el suroeste de la Costa ecuatoriana y reúne 25 cantones alrededor de Guayaquil, su capital. Allí el río que le da nombre se abre hacia el Golfo de Guayaquil, y esa mezcla de agua dulce, manglar y mar marca buena parte de su vida. Según la fuente, la superficie va de unos 15 500 a unos 15 900 km². Hasta 2007 tenía también los cantones de Santa Elena, Salinas y La Libertad, que ese año formaron una provincia propia; Guayas conservó su litoral, con Playas, Posorja, la isla Puná y el Golfo. Sus vecinas son Manabí, Santa Elena, Los Ríos, Bolívar, Chimborazo, Cañar, Azuay y El Oro.

### Llanuras y ríos

Más de la mitad del territorio son llanuras aluviales que casi siempre se elevan menos de 5 m. Las zonas más altas, al este de Bucay y El Triunfo y en Naranjal, van de 200 a 300 m. La cuenca del Guayas abarca cerca del 90 % del territorio provincial; el Daule y el Babahoyo figuran entre sus afluentes principales. Las temperaturas se mueven entre 20 y 28 °C. En los terrenos planos domina el arroz; en las partes onduladas, la caña, el banano y la soya.

### Habitantes y economía

El censo de 2022 del INEC contó 4 391 923 personas, lo que hace de Guayas la más poblada del país; el 85,3 % vive en áreas urbanas. Guayaquil suma 2 746 403 habitantes, seguida de Durán (303 910), Daule (222 446) y Milagro (195 943).

La manufactura es la mayor actividad según el valor agregado de 2018, con el 21,1 % del total. La Prefectura recoge además una cifra de la Cámara de Industrias de Guayaquil: a fines de 2017 la provincia albergaba el 41 % de las empresas del país. Milagro destaca por el azúcar y sus derivados, Yaguachi por el arroz, el cacao y la caña, y en Playas pesan la pesca, el camarón y el turismo.

### Puertos y accesos

El puerto de aguas profundas de Posorja empezó a operar en agosto de 2019, con un canal de 16,5 m de profundidad. El aeropuerto José Joaquín de Olmedo, al norte de Guayaquil, inauguró su terminal actual el 27 de julio de 2006. El puente de la Unidad Nacional enlaza Guayaquil con Durán, y Playas está a unos 97 km de Guayaquil.

### Qué ver y fiestas

El Malecón Simón Bolívar se extiende 2,5 km junto al río, con la Rotonda y la Torre Morisca. Las Peñas, barrio histórico declarado patrimonio nacional en 1982, sube al cerro Santa Ana por 444 escalones. Entre los espacios naturales figuran la isla Santay, sitio Ramsar entre Guayaquil y Durán, el bosque seco de Cerro Blanco y Manglares Churute, un área protegida.

La Prefectura da 1547 como fecha de la fundación definitiva de Guayaquil. Yaguachi celebra a San Jacinto el 16 de agosto, Milagro festeja su cantonización el 17 de septiembre, y en Playas hay Carnaval en febrero y fiesta de San Pedro en junio. La temporada de playa va, según la Prefectura, de enero a abril.

### Fuentes

- [CONGOPE: provincia de Guayas](https://www.congope.gob.ec/provincia-de-guayas/)
- [Prefectura del Guayas: PDOT 2021](https://guayas.gob.ec/wp-content/uploads/2021/08/2021-08-20-PDOT-Guayas.pdf)
- [INEC: Censo 2022, ficha de Guayas](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Guayas.pdf)
- [INEC: Censo 2022, ficha de Pichincha](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Pichincha.pdf)
- [Prefectura del Guayas: cantón Guayaquil](https://guayas.gob.ec/cantones-2/guayaquil/)
- [Prefectura del Guayas: cantón Playas](https://guayas.gob.ec/cantones-2/playas/)
- [Prefectura del Guayas: cantón Durán](https://guayas.gob.ec/cantones-2/duran/)
- [Prefectura del Guayas: cantón Milagro](https://guayas.gob.ec/cantones-2/milagro/)
- [Prefectura del Guayas: cantón Yaguachi](https://guayas.gob.ec/cantones-2/yaguachi/)
- [Municipio de Yaguachi: festividades](https://municipiodeyaguachi.gob.ec/turismo-festividades/)
- [Gobierno de Santa Elena: provincialización](https://www.santaelena.gob.ec/index.php/provincializacion/23santa-elena/santa-elena)
- [Ministerio de Transporte: puerto de Posorja](https://www.mit.gob.ec/puerto-de-aguas-profundas-de-posorja-cumple-un-ano-de-operatividad-y-se-consolida-como-el-primer-puerto-inteligente-de-ecuador/)
- [TAGSA: terminal del aeropuerto de Guayaquil](https://www.tagsa.aero/tagsa-terminal.html)
- [Municipio de Guayaquil: Malecón 2000](https://guayaquil.gob.ec/malecon-2000-guayaquil-naturaleza-entretenimiento/)
- [Guayaquil Turismo](https://turismo.guayaquil.gob.ec/es)
- [Ecuador Chequea: Manglares Churute](https://ecuadorchequea.com/manglares-churute-la-reserva-natural-que-ecuador-abandono/)
$c$ from public.provincias where slug = 'guayas' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Imbabura ocupa el norte de la Sierra ecuatoriana y tiene a Ibarra como capital. Creada en 1824, se divide en seis cantones: Ibarra, Antonio Ante, Cotacachi, Otavalo, Pimampiro y San Miguel de Urcuquí. Sus vecinas son Carchi, en el norte; Pichincha, en el sur; Sucumbíos, en el este, y Esmeraldas, en el oeste. Abarca unos 4 790 km², según el plan de desarrollo provincial.

### Volcanes y lagos

La mayor altura de Imbabura corresponde al Cotacachi, un volcán inactivo de 4 939 m. Otro gran volcán es el Imbabura, de cerca de 4 620 m, que el Instituto Geofísico considera potencialmente activo; su última erupción data de hace unos 8 000 años. En sus faldas se extiende el lago San Pablo, que el Geoparque describe como el mayor lago natural del país.

El plan provincial cuenta 27 lagunas. Entre ellas está Yahuarcocha, a unos 4 km del centro de Ibarra, cuyo nombre kichwa significa «lago de sangre», y Cuicocha, en una caldera de unos 3,5 km de diámetro nacida de una erupción explosiva hace unos 3 100 años. Desde 2019 el territorio forma parte del Geoparque Mundial UNESCO Imbabura, de 479 100 ha.

### Clima

La altura reparte los climas: cálido y seco en el Chota, templado en las cabeceras de los valles, frío en los volcanes y cálido húmedo en Intag y Lita. La temperatura media anual va de 12 a 14 °C en Otavalo a 22 a 24 °C en Lita. Según el INAMHI, citado en el plan provincial, llueve sobre todo de diciembre a mayo, y de junio a noviembre los cielos suelen despejarse más.

### Habitantes y economía

El censo de 2022 contó 469 879 habitantes, el 52,3 % en zonas urbanas. Ibarra reúne a 217 469 y Otavalo a 114 303. Un 64,9 % se identificó como mestizo, un 28,0 % como indígena y un 5,8 % como afroecuatoriano. En el Chota, las comunidades afrodescendientes llegaron durante la colonia a las plantaciones de caña y conservan la música bomba.

En 2022 los servicios ocupaban al 56,9 % de los empleados y la agricultura al 18,4 %. Por superficie, en 2023 predominaron el maíz suave seco, el fréjol, la caña de azúcar, el plátano y el aguacate. En 2021, el 33,21 % del territorio estaba bajo concesión minera.

### Qué ver

El Parque Nacional Cotacachi-Cayapas aporta 39 937,30 ha dentro de Imbabura. En Otavalo, la cascada de Peguche cae unos 20 m en un bosque protector que fue lugar ritual indígena previo al Inti Raymi, y la feria de la Plaza de los Ponchos es otro referente. Chachimbiro ofrece termas con aguas de 25 a 61 grados. Angochagua-Huaraczapas fue distinguido en 2022 como Mejor Pueblo Turístico por ONU Turismo, y San Antonio de Ibarra, Cotacachi y Pimampiro figuran como Pueblos Mágicos.

En Ibarra, a finales de abril se celebra El Retorno, que evoca la vuelta a la ciudad reconstruida en 1872, tras el terremoto de 1868.

### Fuentes

- [Prefectura de Imbabura: PDOT 2023-2027 (reformado)](https://www.imbabura.gob.ec/documentos/2026/pdot/PDOT-2023-2027_reformado.pdf)
- [INEC: Censo 2022, ficha de Imbabura](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Imbabura.pdf)
- [Prefectura de Imbabura: reseña histórica](https://www.imbabura.gob.ec/index.php/imbabura/resena-historica)
- [Prefectura de Imbabura: datos generales](https://www.imbabura.gob.ec/index.php/imbabura/datos-generales)
- [Instituto Geofísico: volcán Imbabura](https://www.igepn.edu.ec/imbabura)
- [Geoparque Imbabura: Cotacachi-Cuicocha](https://geoparque.imbabura.gob.ec/index.php/geoproductos/cotacachi-cuicocha/)
- [Geoparque Imbabura: complejo volcánico Imbabura-Cubilche](https://geoparque.imbabura.gob.ec/index.php/geoproductos/complejo-volcanico-imbabura-cubilche/)
- [Geoparque Imbabura: lago San Pablo y cascada de Peguche](https://geoparque.imbabura.gob.ec/index.php/geoproductos/lago-san-pablo-cascada-de-peguche/)
- [Geoparque Imbabura: laguna de Yahuarcocha](https://geoparque.imbabura.gob.ec/index.php/geoproductos/laguna-de-yahuarcocha/)
- [Geoparque Imbabura: valle del Chota](https://geoparque.imbabura.gob.ec/index.php/geoproductos/valle-del-chota/)
- [Geoparque Imbabura: complejo termal de Chachimbiro](https://geoparque.imbabura.gob.ec/index.php/geoproductos/complejo-termal-chachimbiro)
- [Geoparque Imbabura: valle de Intag](https://geoparque.imbabura.gob.ec/index.php/geoproductos/valle-de-intag/)
- [Geoparque Imbabura: Angochagua](https://geoparque.imbabura.gob.ec/index.php/geoproductos/angochagua)
- [UNESCO: Geoparque Mundial Imbabura](https://www.unesco.org/en/iggp/imbabura-unesco-global-geopark)
- [Municipio de Ibarra](https://www.ibarra.gob.ec)
- [Municipio de Otavalo](https://www.otavalo.gob.ec)
$c$ from public.provincias where slug = 'imbabura' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Quien llega a Loja recorre el último tramo de la Sierra ecuatoriana antes de la frontera con Perú. La provincia, de unos 11 060 km², tiene a Loja como capital y dieciséis cantones. Linda con Azuay y El Oro por el norte, con Zamora Chinchipe por el este y con territorio peruano por el sur y el oeste. Según el censo de 2022, la habitan 485 421 personas, el 60,4 % en zonas urbanas.

### Una provincia con historia propia

El plan de desarrollo provincial recoge dos fundaciones de la capital. La primera ocurrió en 1546, en el valle de Garrochamba, con el nombre de La Zarza. La definitiva la hizo el capitán Alonso de Mercadillo el 8 de diciembre de 1548, en el valle de Cuxibamba. La ciudad proclamó su independencia de España en noviembre de 1820. En 1824, en tiempos de la Gran Colombia, se creó la provincia, con cuatro cantones: Loja, Zaruma, Cariamanga y Catacocha. El 23 de julio es la fecha que da el plan provincial.

Con los años su territorio se redujo. Zaruma pasó a El Oro en 1897, y hoy la provincia cuenta 24 parroquias urbanas y 78 rurales. El cantón Loja reúne a 250 028 habitantes, algo más de la mitad del total.

### Relieve y clima

Aquí la cordillera pierde su orden y se enreda en nudos y hoyas. El plan provincial la describe como la región de relieve más irregular del país. La altitud va de 120 a 3 880 m s. n. m., y la temperatura media anual, de 6 a 26 °C. La capital, a 2 064 m, registra 16 °C y unos 913 mm de lluvia al año. Catamayo, en un valle más bajo, tiene 24,3 °C y apenas 378 mm.

El 65 % del territorio drena por la cuenca del Catamayo, que al unirse con el Macará forma el sistema Catamayo-Chira, rumbo al Pacífico peruano. La ciudad de Loja, en cambio, pertenece a la cuenca del Santiago, que vierte al Atlántico. Las lagunas del Compadre también desaguan hacia el oriente.

### Naturaleza protegida

El Parque Nacional Podocarpus, declarado el 15 de diciembre de 1982, tiene 146 280 ha y se comparte con Zamora Chinchipe. Hacia el noroeste, en el límite con El Oro, se extiende el área fósil de Puyango, un bosque convertido en piedra.

### Campo, caminos y mesa

La caña de azúcar se concentra en La Toma, en Catamayo, y los productores citan sobre todo el fréjol, el arroz, el café y el maíz duro. La Panamericana enlaza Saraguro, Loja, Catamayo, Catacocha y Macará.
Saraguro figura entre las ciudades declaradas Patrimonio Cultural del Ecuador y sigue siendo referente de la cultura indígena saraguro. Cada año la romería de la Virgen del Cisne lleva la imagen desde su parroquia hasta la capital, y abre una fiesta religiosa, turística y comercial. La oferta turística incluye el centro colonial de Loja, el parque Jipiro y Vilcabamba, conocida por su fama de longevidad. En la mesa destacan la cecina, el repe y la arveja con guineo.

### Fuentes

- [Prefectura de Loja: PDOT 2019](https://prefecturaloja.gob.ec/documentos/lotaip/2019/PDOT-2019.pdf)
- [INEC: Censo 2022, ficha de Loja](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Loja.pdf)
- [Ministerio del Ambiente: Plan de Manejo del Parque Nacional Podocarpus (2014)](http://maetransparente.ambiente.gob.ec/documentacion/Biodiversidad/Plan%20de%20Manejo%20Podocarpus%2017abril2014%20FIN.pdf)
- [CONGOPE: provincia de Loja](https://www.congope.gob.ec/provincia-de-loja/)
- [CONGOPE: turismo en Loja](https://www.congope.gob.ec/turismo-loja/)
$c$ from public.provincias where slug = 'loja' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Los Ríos es una provincia de llanura y de agua, en el Litoral ecuatoriano. Babahoyo es su capital y la provincia se reparte en trece cantones: Baba, Babahoyo, Buena Fe, Mocache, Montalvo, Palenque, Puebloviejo, Quevedo, Quinsaloma, Urdaneta, Valencia, Ventanas y Vinces. Según el CONGOPE, su superficie ronda los 7 200 km². Limita con Santo Domingo de los Tsáchilas, Cotopaxi, Bolívar y Guayas, y Manabí queda hacia el noroeste. El eje fluvial es el Babahoyo, formado por los aportes del Catarama, el San Pablo, el Zapotal, el Puebloviejo y el Vinces. Al juntarse con el Daule, da origen al Guayas.

### Historia y habitantes

Babahoyo proclamó su independencia en octubre de 1820, un día 11. Cuatro décadas después, en octubre de 1860, un día 6, un decreto de Gabriel García Moreno creó la provincia y dejó a Babahoyo como capital provisional.

El censo de 2022 del INEC contó 898 652 habitantes, frente a 778 135 en 2010. La ciudad más poblada no es la capital: el cantón Quevedo reúne 206 008 personas y supera a Babahoyo, con 178 509. Les sigue Vinces, con 80 909.

### Una economía de cultivos

La tierra explica buena parte de la identidad provincial. Según la Encuesta de Superficie y Producción Agropecuaria Continua (ESPAC) de 2024, Los Ríos aportó el 39,8 % de la producción nacional de banano, el 30,4 % del cacao, el 28,6 % de la palma africana y el 43,8 % del maíz duro. En el cantón Babahoyo, la población se dedica sobre todo al arroz y al banano.

### Agua y bosque

El humedal Abras de Mantequilla, en Vinces, Baba y Puebloviejo, figura como sitio Ramsar desde el año 2000, con unas 22 500 ha, según el registro internacional. Otro refugio verde es Jauneche, en el cantón Palenque: un Bosque Protector de 138 ha, declarado en 1987 y vinculado a una estación científica de la Universidad de Guayaquil.

### Qué ver y cuándo celebrar

En Babahoyo, la Casa de Olmedo se asocia con el poeta José Joaquín de Olmedo, y el malecón 9 de Octubre bordea el río, con viviendas flotantes. A unos 8,5 km de la ciudad se levanta el cerro Cacharí, un macizo rocoso que sobresale en medio de la llanura aluvial. También hay un sitio arqueológico, La Tola. En Valencia, el CONGOPE destaca un río de aguas claras apto para la pesca, los paseos en bote y las caminatas.

La cocina local se apoya en el río. El CONGOPE menciona el encanutado de bocachico, un pescado asado dentro de una caña, el bollo de pescado con salsa de maní y la chicha de chontilla.

El calendario reúne varias fechas:

- 27 de mayo: cantonización de Babahoyo.
- Septiembre: fiestas de la Virgen de la Merced, con procesión el 24 en Babahoyo y novena del 15 al 23 en Quevedo.
- 6 de octubre: aniversario de la provincia.
- Octubre: rodeo montubio en varios sitios de la provincia.

### Fuentes

- [CONGOPE: provincia de Los Ríos](https://www.congope.gob.ec/provincia-de-los-rios/)
- [CONGOPE: turismo en Los Ríos](https://www.congope.gob.ec/turismo-los-rios/)
- [Municipio de Babahoyo: historia](https://babahoyo.gob.ec/historia)
- [AME: cantón Babahoyo](https://repositorio.ame.gob.ec/canton-babahoyo/)
- [AME: Jauneche, un bosque protector del cantón Palenque](https://repositorio.ame.gob.ec/jauneche-un-bosque-protector-que-engalana-al-canton-palenque/)
- [INEC: Censo 2022, ficha de Los Ríos](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Los-Rios.pdf)
- [INEC: presentación de resultados ESPAC 2024](https://www.ecuadorencifras.gob.ec/documentos/web-inec/Estadisticas_agropecuarias/espac/2024/Presentacion_de_resultados_ESPAC_2024.pdf)
- [Ramsar: Abras de Mantequilla](https://rsis.ramsar.org/es/ris/1023)
- [Municipio de Quevedo: cronograma de actividades](https://quevedo.gob.ec/cronograma-de-actividades-religiosas-y-culturales/)
$c$ from public.provincias where slug = 'los-rios' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Manabí se extiende sobre la costa central del Ecuador, de cara al Pacífico, y tiene a Portoviejo como capital. Se divide en 22 cantones y limita con Esmeraldas al norte, con Santa Elena al sur y con Santo Domingo de los Tsáchilas, Los Ríos y Guayas al este. Su superficie ronda los 19 500 km², aunque las cifras oficiales difieren un poco entre sí. Uno de sus cantones se llama Pichincha.

### Estaciones y paisajes protegidos

Según el plan de desarrollo provincial, hay una estación lluviosa, de enero a mayo, y otra seca, de junio a diciembre. En el litoral semiárido la temperatura suele moverse entre 20 y 26 °C; en la zona central, la más extensa, supera los 24 °C durante la época seca; y en el noreste húmedo oscila entre 15 y 24 °C, con lluvias de 1 000 a 2 000 mm anuales.

El Parque Nacional Machalilla reúne bosques secos y ambientes marinos, con playas como Los Frailes, varios islotes y la Isla de la Plata, que forma parte del parque y no es una reserva aparte. En la desembocadura del río Chone, el Refugio de Vida Silvestre Isla Corazón y Fragata protege un manglar donde, según el Ministerio del Ambiente, anidan de las mayores colonias de fragatas del país.

### Habitantes y trabajo

El censo de 2022 del INEC contó 1 592 840 personas, lo que convierte a Manabí en la tercera provincia más poblada. El 58 % vive en áreas urbanas, y Portoviejo, con 322 925 habitantes, y Manta, con 271 145, son los cantones más numerosos.

La economía descansa sobre el campo y el mar. Entre los cultivos, el cacao ocupa la mayor superficie y el maíz aporta el mayor volumen. En ganadería, el plan provincial ubica a Manabí en primer lugar nacional en carne bovina, según datos del INEC de 2019. Manta es el primer puerto pesquero del país y el primero en desembarques de atún del Pacífico suroriental.

### Sombreros, mesa y memoria

El tejido tradicional del sombrero de paja toquilla fue inscrito por la UNESCO en 2012 en la Lista Representativa del Patrimonio Cultural Inmaterial de la Humanidad. Montecristi y Jipijapa figuran entre los lugares ligados a este oficio, que también se practica en Santa Elena, Azuay, Cañar y Morona Santiago.

En Montecristi se levanta el Centro Cívico Ciudad Alfaro, un conjunto de 5,4 hectáreas con forma de cóndor. Guarda el mausoleo de Eloy Alfaro y los escaños de la Asamblea Constituyente de 2008, que sesionó allí.

La cocina local se apoya en el maní, el plátano verde y el pescado. El viche es una sopa espesa con verde, caldo de maní y pescado o marisco; la tonga lleva arroz, plátano y pollo en salsa de maní, envueltos en hoja. Entre las celebraciones, el plan provincial recoge Blancos y Negros, dedicada a San Pedro y San Pablo, que suele darse entre junio y julio.

### Fuentes

- [Gobierno Provincial de Manabí: PDOT Manabí 2030](https://www.manabi.gob.ec/wp-content/uploads/2022/09/PDOT_Manabi_2030_v1.1..pdf)
- [INEC: Censo 2022, ficha de Manabí](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Manabi.pdf)
- [CONGOPE: provincia de Manabí](https://www.congope.gob.ec/provincia-de-manabi/)
- [CONGOPE: turismo en Manabí](https://www.congope.gob.ec/turismo-manabi/)
- [Ministerio del Ambiente: áreas protegidas de la Costa](https://www.ambienteyenergia.gob.ec/wp-content/uploads/sites/2/downloads/2025/01/COSTA-3.pdf)
- [Ministerio de Educación: sombrero de paja toquilla, patrimonio de la UNESCO](https://educacion.gob.ec/cultura/ecuador-conmemora-el-decimo-aniversario-de-la-declaratoria-del-tejido-de-sombrero-de-paja-toquilla-como-patrimonio-cultural-inmaterial-de-la-humanidad/)
- [Ministerio de Educación: Centro Cívico Ciudad Alfaro](https://educacion.gob.ec/cultura/centro-civico-ciudad-alfaro-un-destino-cultural-de-manabi/)
$c$ from public.provincias where slug = 'manabi' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Por superficie, Morona Santiago es la segunda provincia del país, con unos 24 000 km², pero sus 192 508 habitantes de 2022 se reparten en un territorio de espacios amplios y comunidades dispersas. Su capital es Macas, fundada por los españoles en agosto de 1563 como Nuestra Señora del Rosario de Macas. La provincia tiene 12 cantones: Gualaquiza, Huamboya, Limón Indanza, Logroño, Morona, Pablo Sexto, Palora, San Juan Bosco, Santiago, Sucúa, Taisha y Tiwintza. Sevilla Don Bosco, que a veces se cuenta como cantón, es una parroquia de Morona. En total hay 58 parroquias, 13 urbanas y 45 rurales.

### Montaña, selva y un volcán

El relieve baja desde las alturas andinas hasta la llanura amazónica. En ese tránsito se levanta el Sangay, un estratovolcán de 5 230 m que los registros del Instituto Geofísico dan por eruptivo de forma constante desde 1628. Su fase más intensa comenzó en 2019, y los lahares del río Volcán llegaron a turbiar y represar en parte el Upano.

El Parque Nacional Sangay aporta 364 698 ha dentro de la provincia, el 15,19 % de su superficie. Con las demás áreas protegidas, entre ellas la Reserva Biológica El Quimi, el Parque Binacional El Cóndor y Río Negro Sopladora, suman 422 560 ha.

### Un clima que depende de la altura

Bajo los 900 m, donde queda cerca del 44 % del territorio, la temperatura media anual va de 18 a 28 °C y la lluvia llega a 3 000 o 4 000 mm. Entre 900 y 2 000 m oscila de 12 a 24 °C. Por encima de los 2 000 m baja de 12 °C. Los extremos son Taisha, con 28 °C, y el Sangay, con registros de -4 °C. El valle del Upano, a 995 m y a 4,3 km de Macas, ronda los 20 a 22 °C.

### Una provincia mayoritariamente indígena

En el censo de 2022, el 58,6 % de la población se identificó como indígena y el 39,9 % como mestiza. Predominan los pueblos shuar y achuar, y según el Ministerio de Cultura es la provincia con mayor territorio indígena. Cerca de dos tercios de los habitantes viven en zonas rurales.

### Producción y caminos

La pitahaya es el producto agrícola más conocido: según el plan provincial de 2019, cerca del 70 % se exportaba a Hong Kong, Estados Unidos, Japón y Europa. A ella se suman el cacao, la ganadería bovina y el comercio de productos del campo. La Troncal Amazónica, abierta en 2006, y la Transversal Austral, de 2011, acortaron el aislamiento. En el oriente profundo todavía pesan los ríos y las pistas aéreas de Taisha, Gualaquiza, Patuca y Santiago.

### Qué ver y probar

El plan provincial cuenta unos 231 atractivos, aunque menos de la quinta parte se aprovecha. Entre los principales figuran el Sangay, el río Upano y la cultura shuar y achuar. En Limón Indanza está la Cueva de los Tayos, un atractivo cultural y turístico, no un área protegida.

En la mesa aparece el ayampaco, plato típico, junto con la chicha de yuca y la guayusa, una planta ancestral que se toma como infusión.

### Fuentes

- [Gobierno Provincial de Morona Santiago: PDOT 2019-2023, Tomo I, diagnóstico](https://moronasantiago.gob.ec/wp-content/uploads/2022/04/TOMO-I-_FASE-DIAG-COMPON.pdf)
- [INEC: Censo 2022, ficha de Morona Santiago](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Morona-Santiago.pdf)
- [CONGOPE: provincia de Morona Santiago](https://www.congope.gob.ec/provincia-de-morona-santiago/)
- [Instituto Geofísico: volcán Sangay](https://www.igepn.edu.ec/sangay)
- [Ministerio de Cultura: Morona Santiago](https://educacion.gob.ec/cultura/morona-santiago-reliquia-de-oriente-y-selva-enigmatica-sin-tiempo-de-gente-de-esfuerzo-y-trabajo/)
$c$ from public.provincias where slug = 'morona-santiago' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Entre los páramos de la Cordillera Real y las llanuras del Oriente, Napo se extiende por unos 12 542 km² en el centro norte de la Amazonía ecuatoriana. Su capital es Tena, a 193 km de Quito y a 78 km de Puyo. Limita con Sucumbíos al norte, Orellana al este y Pastaza al sur, mientras que por el occidente toca tres provincias de la Sierra: Pichincha, Tungurahua y Cotopaxi. La forman cinco cantones, Tena, Archidona, Carlos Julio Arosemena Tola, El Chaco y Quijos, con 25 parroquias, cinco de ellas urbanas.

### Una provincia que se fue achicando

Según el plan de desarrollo provincial (PDOT), Napo fue creada el 15 de diciembre de 1920 y reconocida como tal en octubre de 1959, según el Registro Oficial 969. Con el tiempo perdió territorio: de ella se desprendieron Sucumbíos, en 1989, y Orellana, en 1998.

### Volcanes y áreas protegidas

El PDOT da al Antisana 5 758 m y lo considera potencialmente activo; el Quilindana llega a 4 876 m y está dormido; el Sumaco alcanza 3 732 m; el Reventador, de 3 562 m, es el más inquieto: el Instituto Geofísico lo registra en erupción continua desde 2002.

Más de la mitad del territorio, el 53,72 %, está protegido: unas 673 264 ha repartidas en seis áreas, entre ellas el parque nacional Cayambe Coca (181 376 ha dentro de Napo), el Sumaco Napo-Galeras (168 279 ha), la reserva ecológica Antisana (120 575 ha), el parque Llanganates (106 758 ha) y la reserva biológica Colonso Chalupas (93 181 ha). Además, la UNESCO declaró el 10 de noviembre de 2000 la Reserva de Biosfera Sumaco, que abarca un millón de hectáreas en Napo, Orellana y Sucumbíos.

### Lluvia y ríos

El clima es húmedo, con una temperatura media actual de 24 a 26 °C. Llueve más de marzo a mayo, entre 240 y 270 mm al mes, mientras que entre julio y septiembre baja a cerca de 150 mm. Al sureste caen entre 3 000 y 3 600 mm al año; al noroeste, menos de 1 500 mm.

Todo el territorio pertenece a la cuenca del Napo, el río más caudaloso del país, con 491,85 km en Ecuador y un caudal de 1 800 m³/s. Se forma en el sur de la provincia con aguas de la Cordillera Real, entre ellas las del Jatunyacu, y Puerto Napo se levanta en esa confluencia.

### Gente y cultivos

El censo de 2022 contó 131 675 habitantes, el 33,9 % en zonas urbanas y con una edad mediana de 24 años. El 65,0 % se identificó como indígena y el 32,5 % como mestizo. Tena reúne a 80 816 personas y Archidona a 30 488.

En el campo domina el cacao: en 2022 hubo 6 822 ha plantadas y 3 713 t, y el PDOT atribuye a la población kichwa cerca del 80 % de los productores. Siguen en importancia la yuca, el plátano y el maíz duro, y el café apenas ocupa 125 ha. En Rukullakta, la asociación Ruku Kawsay cultiva guayusa en unas 300 ha, con 375 productores.

### Fuentes

- [Gobierno Provincial de Napo: PDOT 2023-2027](https://www.napo.gob.ec/wp-content/uploads/1_pdot_napo-2023_2027.pdf)
- [INEC: Censo 2022, ficha de Napo](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Napo.pdf)
- [CONGOPE: provincia de Napo](https://www.congope.gob.ec/provincia-de-napo/)
- [Instituto Geofísico: volcán Reventador](https://www.igepn.edu.ec/reventador)
- [Instituto Geofísico: volcán Antisana](https://www.igepn.edu.ec/antisana)
$c$ from public.provincias where slug = 'napo' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Orellana no tuvo rango de provincia hasta 1998: antes era un cantón dependiente de Napo. El 28 de julio de ese año un decreto del gobierno interino de Fabián Alarcón la convirtió en provincia, con capital en Puerto Francisco de Orellana, conocida como El Coca. Hoy reúne cuatro cantones (Orellana, Aguarico, La Joya de los Sachas y Loreto) y 32 parroquias, en unos 21 600 a 21 700 km² según la fuente oficial que se consulte.

### Del terremoto al decreto

La idea de una provincia propia surgió en los años ochenta, y entre sus impulsores figuró monseñor Alejandro Labaka. El terremoto del 5 de marzo de 1987 dejó aislado al cantón, y ese agosto se formó en El Coca un comité pro provincialización que llevó el nombre de Labaka. El nombre «Amazonas» se descartó por la situación con Perú. La bandera conserva ese origen: franjas blanca, verde y amarilla, ribete negro por el petróleo y cuatro estrellas, una por cada cantón.

### Lluvia y ríos

La provincia está en la cuenca baja del Napo, una de las de mayor caudal del país. Allí desembocan el Tiputini, el Yasuní, el Cononaco y el Payamino, y hay lagunas como Anangucocha y Jatuncocha. En la serie del INAMHI de 1981 a 2022, la temperatura media mensual fue de 26,6 °C y la lluvia anual fue de 2 839 mm en Nuevo Rocafuerte y de 3 140 mm en El Coca.

### Gente y territorio

El censo de 2022 contó 182 166 habitantes, frente a 84 569 en 2001, y el 59,7 % vive en zonas rurales. Francisco de Orellana reúne 95 130 personas y La Joya de los Sachas 52 444. Aguarico, el cantón más extenso, apenas tiene 6 872 y una densidad de 0,61 habitantes por km². Un 58,3 % se identificó como mestizo y un 37,3 % como indígena; kichwa, shuar y waorani tienen territorios propios.

### Yasuní y otras reservas

El Parque Nacional Yasuní se reparte entre Orellana y Pastaza. En Orellana ocupa 674 883 ha, casi tres cuartas partes en Aguarico. La UNESCO lo designó reserva de biosfera en 1989. En su territorio se extiende la zona intangible para los pueblos tagaeri y taromenane, creada en 1999, donde no se permite actividad extractiva y viven pueblos en aislamiento voluntario. La Reserva Biológica Limoncocha, creada en 1985, es sitio Ramsar desde 1998 y alberga más de 144 especies de aves.

### Caminos, minas y mesa

La red vial estatal es en un 90 % de pavimento flexible. El eje E45A une El Coca con La Joya de los Sachas y Sucumbíos, y con Pastaza por Dayuma; hacia Napo, la ruta por Loreto suma 84,80 km asfaltados. En cambio, la red rural provincial, de unos 3 249 km, es sobre todo de lastre. El aeropuerto de El Coca atiende pasajeros y carga.

Los bloques petroleros y 237 concesiones mineras marcan el uso del suelo. En la mesa aparecen el maito, carne de caza o pescado asado en hojas de bijao, el ayampaco, cocinado al vapor, y el chontacuro, larvas de escarabajo a las brasas.

### Fuentes

- [GAD Provincial de Orellana: historia de la provincia](https://www.gporellana.gob.ec/historia.php)
- [GAD Provincial de Orellana: PDOT 2023-2027](https://www.gporellana.gob.ec/resources/uploads/desarrollo/2024/PDOT%20PROVINCIAL%20FINAL%202023-2027-signed-signed-signed-signed-signed_compressed-comprimido.pdf)
- [INEC: Censo 2022, ficha de Orellana](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Orellana.pdf)
- [CONGOPE: provincia de Orellana](https://www.congope.gob.ec/provincia-de-orellana/)
- [CONGOPE: turismo en Orellana](https://www.congope.gob.ec/turismo-orellana/)
- [UNESCO: Reserva de Biosfera Yasuní](https://www.unesco.org/en/mab/yasuni)
$c$ from public.provincias where slug = 'orellana' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Casi todo lo que se ve en Pastaza es selva. Es la provincia más extensa del Ecuador, con cerca de 29 640 km² según CONGOPE y su plan de desarrollo, y también la de menor densidad: 3,77 habitantes por km². Su capital es Puyo y la integran cuatro cantones: Pastaza, Mera, Santa Clara y Arajuno. La reforma a la Ley Especial de Oriente que la separó de Napo se publicó el 10 de noviembre de 1959, en el Registro Oficial 963.

### De los Andes a la frontera

El terreno baja desde los 3 194 m, en el Parque Nacional Llanganates, hasta los 162 m del extremo oriental, donde empieza el Perú. Por el occidente toca Tungurahua; por el septentrión, Napo y Orellana, y Morona Santiago cierra el límite meridional. Sus ríos pertenecen a tres cuencas: Pastaza, Tigre y Napo. El Tigre nace de la unión del Conambo y el Pindoyacu, y el plan provincial lo describe como navegable todo el año.

El clima es tropical húmedo, con una temperatura que oscila entre 18 y 33 °C y lluvias de 2 000 a 4 000 mm anuales. El bosque cubre más del 93 % del suelo.

### Selva con figura de conservación

Según el plan provincial, el 85,74 % del territorio cae bajo alguna figura de conservación, entre ellas bosques protectores, áreas Socio Bosque y un área provincial creada por ordenanza. Dentro de Pastaza hay 1 168 842 ha de la Reserva de Biosfera Yasuní, en las parroquias Curaray, Río Tigre, Montalvo y Arajuno. El Parque Nacional Yasuní aporta 359 771 ha, y la zona intangible de los tagaeri y los taromenane, refugio de pueblos en aislamiento voluntario, otras 434 664 ha. Llanganates, en cambio, ocupa apenas 14 173 ha, en Mera.

### Siete nacionalidades

Aquí viven siete de las catorce nacionalidades indígenas del país: Kichwa, Shuar, Achuar, Shiwiar, Andwa, Sapara y Waorani. En el censo de 2022, de 111 915 habitantes, el 50,8 % se identificó como indígena y el 47,2 % como mestizo; la población urbana es el 34,3 %.

Un caso conocido es Sarayaku, pueblo kichwa a orillas del Bobonaza, a 65 km de Puyo. El 27 de junio de 2012 la Corte Interamericana de Derechos Humanos declaró responsable al Estado por violar su derecho a la consulta, a la propiedad comunal y a la identidad cultural, a raíz de un permiso petrolero otorgado sin consulta previa.

### Campo y caminos

Solo cerca del 5 % del suelo es agropecuario. Según el plan provincial, el plátano ocupa la mayor superficie, la caña de azúcar da el mayor volumen de producción y la yuca encabeza los cultivos transitorios. Los pueblos indígenas mantienen la chacra, donde combinan plátano, yuca y frutales para el consumo propio. También hay piscicultura, con la tilapia como especie principal.

Desde Puyo salen la carretera a Baños, que enlaza con la Sierra, y la Troncal Amazónica hacia Tena y Macas. Muchas comunidades carecen de vía, de modo que dependen de 85 pistas aéreas y de unos 1 647 km de ríos navegables. El aeropuerto Río Amazonas funciona en Shell.

### Fuentes

- [Gobierno Provincial de Pastaza: actualización del PDOT al 2035](https://pastaza.gob.ec/baselegal/planes/actualizacion_pdot_provincia_pastaza_al_2035.pdf)
- [INEC: Censo 2022, ficha de Pastaza](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Pastaza.pdf)
- [CONGOPE: provincia de Pastaza](https://www.congope.gob.ec/provincia-de-pastaza/)
- [Gobierno Provincial de Pastaza: historia de la provincia](https://pastaza.gob.ec/pastaza/historia-de-la-provincia-de-pastaza/)
- [Gobierno Provincial de Pastaza: información de la provincia](https://pastaza.gob.ec/pastaza/informacion/informacion-de-la-provincia-de-pastaza/)
- [Corte IDH: sentencia del caso Sarayaku](https://www.corteidh.or.cr/docs/casos/articulos/seriec_245_esp.pdf)
$c$ from public.provincias where slug = 'pastaza' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Pichincha, en la Sierra del Ecuador, tiene a Quito como capital y se organiza en ocho cantones: Quito, Cayambe, Mejía, Pedro Moncayo, Pedro Vicente Maldonado, Puerto Quito, Rumiñahui y San Miguel de los Bancos. Limita con Imbabura y Esmeraldas al norte, con Cotopaxi al sur, con Napo y Sucumbíos al este y con Santo Domingo de los Tsáchilas al oeste. Su superficie ronda los 9 500 km², aunque las fuentes oficiales no coinciden del todo en la cifra.

### Del páramo al subtrópico

En el centro y el este de la provincia dominan los volcanes y los valles andinos; hacia el noroccidente el terreno desciende poco a poco hacia la Costa. El volcán Cayambe llega a 5 790 m y conserva, según el Instituto Geofísico, un casquete glaciar de unos 22 km² por encima de los 4 800 m.

El clima depende de la altura. Según el Gobierno Provincial, las temperaturas medias van de unos 8 a 24 °C, desde el bosque húmedo del occidente hasta el páramo. En las lagunas de Mojanda la media ronda los 8 °C y las noches pueden bajar de los cero grados. Quito se asienta a unos 2 850 m y, según datos climáticos de referencia, sus meses más secos suelen ser de junio a septiembre.

### Ciudades y habitantes

El censo de 2022 del INEC contó 3 089 473 habitantes, lo que sitúa a Pichincha como la segunda provincia más poblada del país, detrás de Guayas. Cerca del 63 % vive en áreas urbanas. Quito reúne a 2 679 722 personas, y Rumiñahui, Cayambe y Mejía superan cada uno los 100 000. En Tababela, al este de la capital, el aeropuerto Mariscal Sucre abrió en 2013.

### Qué ver y cuándo ir

El Centro Histórico de Quito fue inscrito en la lista de Patrimonio Mundial de la UNESCO en 1978, junto con Cracovia. En él se alza la Basílica del Voto Nacional, un templo neogótico de torres de 115 m.

Fuera de la ciudad, Cochasquí conserva quince pirámides truncadas y veintiuna tolas de la cultura Quitu-Cara, a unos 52 km al norte de la capital. Las tres lagunas de Mojanda, en el límite con Imbabura, forman parte del área de conservación Mojanda-Cambugán, declarada en 2022. En el noroccidente, el Chocó Andino de Pichincha es reserva de biosfera desde 2018, y las montañas del este albergan los parques nacionales Cayambe-Coca, compartido con Imbabura, Napo y Sucumbíos, y Antisana. Al sur, en Mejía, el Refugio de Vida Silvestre Pasochoa protege un tramo de bosque andino.

El calendario festivo gira en torno a unas pocas citas. Las Fiestas de Quito se celebran alrededor del 6 de diciembre, fecha con la que tradicionalmente se recuerda la fundación de 1534. En Cayambe, las fiestas de San Pedro y el Inti Raymi suelen tener lugar a finales de junio. En Machachi, el Paseo Procesional del Chagra se realiza por lo general en julio, y en Sangolquí la Fiesta del Maíz y del Turismo llega en septiembre. Fechas y horarios se confirman en los sitios oficiales de turismo.

### Fuentes

- [Gobierno Provincial de Pichincha: información general](https://www.pichincha.gob.ec/pichincha/datos-de-la-provincia/95-informacion-general)
- [CONGOPE: provincia de Pichincha](https://www.congope.gob.ec/provincia-de-pichincha/)
- [INEC: Censo 2022, ficha de Pichincha](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Pichincha.pdf)
- [Instituto Geofísico: volcán Cayambe](https://www.igepn.edu.ec/cayambe)
- [Quito Turismo: Quito, Patrimonio Cultural de la Humanidad](https://www.quito-turismo.gob.ec/news/quito-patrimonio-cultural-de-la-humanidad/)
- [Quito Informa: Quito, Patrimonio Cultural de la Humanidad](https://www.quitoinforma.gob.ec/2023/04/18/quito-patrimonio-cultural-de-la-humanidad/)
- [Quito Informa: área protegida Mojanda-Cambugán](https://www.quitoinforma.gob.ec/2022/02/22/quito-declara-nueva-area-natural-protegida-a-27-mil-hectareas-de-mojanda-cambugan-2/)
- [Pichincha es Turismo: lagunas de Mojanda](https://pichinchaesturismo.com/es-ec/pichincha/pedro-moncayo/lagunas/lagunas-mojanda-a933b37f9)
- [Pichincha es Turismo: Parque Arqueológico Cochasquí](https://pichinchaesturismo.com/es-ec/pichincha/pedro-moncayo/zonas-arqueologicas/parque-arqueologico-cochasqui-amg8kg5fk)
- [Pichincha es Turismo: aeropuerto de Quito](https://pichinchaesturismo.com/es-ec/pichincha/quito/aeropuertos/aeropuerto-internacional-quito-aee8ab662)
- [Gobierno Provincial: Reserva de Biosfera Chocó Andino](https://www.pichincha.gob.ec/component/content/article/810-reserva-de-biosfera-del-choco-andino-de-pichincha?catid=137&Itemid=437)
- [Pichincha es Turismo: Fiesta del Maíz, Sangolquí](https://pichinchaesturismo.com/es-ec/pichincha/ruminahui/fiestas-tradicionales/fiesta-maiz-turismo-sangolqui-a771fd172)
- [Quito Informa: Fiestas de Quito](https://www.quitoinforma.gob.ec/2025/12/01/quito-en-modo-fiestas-planes-imperdibles-para-cada-dia-de-esta-semana/)
$c$ from public.provincias where slug = 'pichincha' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Santa Elena ocupa la península suroccidental de la Costa ecuatoriana, una franja de tierra baja y seca que se adentra en el Pacífico. La capital comparte el nombre y hay tres cantones: Santa Elena, La Libertad y Salinas. Al norte limita con Manabí y al este con Guayas; el océano la rodea por el oeste y el sur. Nació como provincia en 2007, un 7 de noviembre, con territorio del antiguo Guayas. Su superficie ronda los 3 700 km², aunque las fuentes oficiales no coinciden: el CONGOPE indica 3 690,17 y el Gobierno Provincial, 3 762,8.

### Un litoral seco

Sobre esta costa pesa el influjo de la fría Humboldt, que la mantiene árida, con nieblas y lloviznas débiles junto al mar. En la estación de Salinas, según datos del INAMHI, el promedio anual ronda los 23,4 °C: agosto es el mes más fresco (21,0 °C) y marzo el más cálido (26,1 °C). Llueve unos 150 mm al año, sobre todo en febrero y marzo; de junio a diciembre casi no cae agua.

En la cordillera Chongón-Colonche subsiste bosque seco y húmedo. En 2022 el Consejo Provincial aprobó un sistema de áreas de conservación y uso sostenible de 112 450 hectáreas. En el mar, según las referencias consultadas, figuran la Reserva Marina El Pelado y la reserva Puntilla de Santa Elena.

### Habitantes y economía

El censo de 2022 del INEC contó 385 735 habitantes. Santa Elena reúne a 186 687 personas, La Libertad a 112 247 y Salinas a 86 801; el 52,3 % vive en áreas urbanas.

El Gobierno Provincial menciona como sectores principales la pesca, la refinación de petróleo, el turismo, las artesanías y la hotelería de playa. Hay además puerto y el aeropuerto General Ulpiano Páez, en Salinas, inaugurado en enero de 2014 sobre la antigua base aérea. La E40 enlaza Guayaquil con Santa Elena y Salinas; su tramo hasta Salinas se entregó rehabilitado en julio de 2023. La ruta del Spondylus (E15) llega desde Manabí y se une a la E40 en la ciudad de Santa Elena.

### Qué ver y cuándo ir

Según el Gobierno Provincial, el punto más saliente de la costa continental está en La Chocolatera, en Salinas. De junio a septiembre transcurre allí la temporada de la ballena jorobada, visible incluso desde tierra. Ayangue, cerca del islote El Pelado, es comunidad de pesca y buceo; Playa Rosada tiene arena de ese color, y Montañita es balneario de surf.

La historia antigua se recorre en museos:

- Los Amantes de Sumpa, sobre un cementerio de la cultura Las Vegas, con dos jóvenes enterrados abrazados.
- El Museo Valdivia, descrito como el primer museo comunitario del país sobre un sitio arqueológico.
- El Museo Real Alto, dedicado a un poblado de casas sobre montículos en herradura.

El 7 de noviembre se recuerda la provincialización. Según fuentes no oficiales, la fiesta de Santa Elena cae el 18 de agosto y la de San Pedro el 29 de junio, y la agenda local anota el festival de cometas de Olón a finales de abril. Las fechas se confirman en sitios oficiales.

### Fuentes

- [CONGOPE: provincia de Santa Elena](https://www.congope.gob.ec/provincia-de-santa-elena/)
- [Asamblea Nacional: aniversario de la provincialización de Santa Elena](https://www.asambleanacional.gob.ec/es/blogs/maria-aquino/75448-xiv-aniversario-de-provincializacion-de-santa)
- [Gobierno Provincial de Santa Elena: información general](https://www.santaelena.gob.ec/index.php/santa-elena/23-santa-elena/santa-elena.html)
- [Gobierno Provincial de Santa Elena: balnearios](https://www.santaelena.gob.ec/index.php/balnearios)
- [Gobierno Provincial de Santa Elena: museos](https://www.santaelena.gob.ec/index.php/museos)
- [INEC: Censo 2022, ficha de Santa Elena](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Santa_Elena.pdf)
- [IGM: clima e hidrología de Santa Elena](https://www.geoportaligm.gob.ec/geodescargas/santa_elena/mt_santa_elena_clima_e_hidrologia.pdf)
- [Presidencia: vías en Santa Elena, julio de 2023](https://www.presidencia.gob.ec/wp-content/uploads/downloads/2023/07/2023.07.12-VIAS-EN-SANTA-ELENA.pdf)
- [MIT: inauguración del aeropuerto de Salinas](https://www.mit.gob.ec/aeropuerto-de-salinas-se-inauguro-con-el-anuncio-de-proximas-rutas-comerciales/)
- [Ministerio del Ambiente: ballenas jorobadas en Santa Elena](https://www.ambienteyenergia.gob.ec/ambiente/primer-avistamiento-de-ballenas-jorobadas-en-las-costas-de-santa-elena/)
- [El Universal: sistema provincial de áreas protegidas de Santa Elena](https://www.eluniverso.com/larevista/ecologia/santa-elena-creo-un-sistema-provincial-de-areas-protegidas-para-conservar-112450-hectareas-de-bosque-seco-y-humedo-nota/)
- [Ministerio de Educación: museo Amantes de Sumpa](https://educacion.gob.ec/cultura/el-museo-amantes-de-sumpa-abrira-sus-puertas-este-primero-de-mayo/)
$c$ from public.provincias where slug = 'santa-elena' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Quien viaja de Quito a la costa por carretera atraviesa tarde o temprano Santo Domingo de los Tsáchilas, a 133 km de la capital. La provincia nació de una consulta popular celebrada en noviembre de 2006, en la que ganó el sí con un 83,61 %, y se separó de Pichincha con una ley que el Registro Oficial publicó el 6 de noviembre de ese año. Su capital es Santo Domingo, y la forman dos cantones: Santo Domingo y La Concordia, este último parte de Esmeraldas hasta 2013. Abarca unos 3 800 km² y limita con Pichincha, Cotopaxi, Los Ríos, Manabí y Esmeraldas.

### Del piedemonte a la llanura

El territorio baja desde las estribaciones exteriores de los Andes, que alcanzan unos 3 020 m en Chiriboga, hasta zonas de apenas 120 m en el occidente. La capital provincial se asienta a unos 600 m. Es un trópico húmedo, con temperaturas medias de 22 a 23 °C y de 3 000 a 4 000 mm de lluvia anual, algo más escasa hacia mediados de año.

Los ríos y los bosques ocupan buena parte del mapa. El Toachi es el curso más conocido, y el plan de desarrollo provincial registra bosques protectores como Toachi Pilatón, con unos 8 100 ha, y Río Lelia, con unos 3 200 ha. En el extremo sur de la provincia llega además una franja de la Reserva Ecológica Ilinizas.

### Habitantes y economía

El censo de 2022 contó 492 969 personas, el 75,1 % en zonas urbanas: 441 583 en el cantón Santo Domingo y 51 386 en La Concordia. Se identificó como mestizo el 89,9 %, y como indígena el 1,4 %.

La ciudad funciona como nudo comercial entre la Sierra y la Costa y como mercado ganadero. Desde allí parten vías hacia Quito, Guayaquil (287 km), Esmeraldas (185 km) y Manta (257 km). En el campo dominan la palma aceitera, el plátano, el cacao y la yuca; en la autopista hacia Esmeraldas se cultivan además palma africana, abacá y cacao para exportar.

### El pueblo Tsáchila

El nombre de la provincia recuerda a los tsáchilas, pueblo originario que habla tsa'fiki y que, según el Gobierno Provincial, se tiñe de rojo con achiote. Su año nuevo es la Kasama, palabra que une «kasa», nuevo, y «ma», día. Se celebra entre marzo y abril, con fecha distinta cada año y sede rotatoria entre las comunidades. Reúne rituales, música, danza, juegos ancestrales y gastronomía; los poné, sanadores del pueblo, guían ceremonias de purificación en el río. Entre los platos propios figura el ayampaco, pescado de río cocinado dentro de una hoja de bijao.

### Qué ver

Además de visitar las comunidades, se pueden recorrer balnearios y cascadas, practicar rafting, tubing y kayak, o seguir la Vía Aventura en bicicleta. El Jardín Botánico Padre Julio Marrero, de 7 ha, guarda un orquideario con unas 200 especies. Dentro de la ciudad, el cerro Bombolí, con su iglesia y su mirador, es la elevación que el Gobierno Provincial cita como principal.

### Fuentes

- [Gobierno Provincial: provincialización](https://gptsachila.gob.ec/provincializacion/)
- [Gobierno Provincial: datos generales](https://gptsachila.gob.ec/datos-generales/)
- [Gobierno Provincial: PDOT provincial](https://www.gptsachila.gob.ec/dtransparencia/PDOT_Provincial.pdf)
- [INEC: Censo 2022, ficha de Santo Domingo de los Tsáchilas](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Santo_Domingo_De_Los_Tsachilas.pdf)
- [CONGOPE: turismo en Santo Domingo](https://www.congope.gob.ec/turismo-santo-domingo/)
- [Ministerio de Educación: la Kasama tsáchila](https://educacion.gob.ec/cultura/el-kasama-tsachila-da-inicio-al-ano-nuevo/)
$c$ from public.provincias where slug = 'santo-domingo-de-los-tsachilas' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Pocas provincias del país deben tanto de su fisonomía actual a una sola década como Sucumbíos a los años setenta. La colonización promovida por el Estado y la industria petrolera transformaron una selva de ríos y pueblos originarios en un territorio de siete cantones, con Nueva Loja, fundada el 20 de junio de 1979, como capital. La provincia se creó en febrero de 1989 y, con 18 084 km², según el Gobierno Provincial y el Congope, abarca cerca del 7 % del territorio nacional. En el extremo noreste, el río Putumayo marca la frontera con Colombia; al este está Perú, al sur Orellana y Napo, y hacia el occidente se alza la cordillera andina.

### Quiénes la habitan

El censo de 2022 registró 199 014 personas, frente a 174 481 en 2010 y 126 599 en 2001: el ritmo de crecimiento pasó de 3,6 % a 1,1 % anual. El 59,3 % vive en áreas rurales. Lago Agrio reúne a 105 044 habitantes y Shushufindi a 50 826, mientras que Sucumbíos, con cabecera en La Bonita, apenas suma 3 174.
En 2022, un 77,4 % se identificó como mestizo, un 16,3 % como indígena y un 4,6 % como afroecuatoriano. El plan provincial cita las nacionalidades shuar, cofán, siona, secoya, awá y kichwa.

### Ríos, lluvia y un volcán inquieto

El Aguarico desemboca en el Napo, y el Cuyabeno, afluente suyo, atraviesa la reserva que lleva su nombre. El Lagartococha forma parte del límite con Perú. Según el Gobierno Provincial, el territorio suma unos 30 ríos, 40 cascadas, más de 1 800 especies animales y 4 000 de flora, cifras con las que el plan lo presenta como el más biodiverso del país.

La lluvia supera los 3 000 mm al año y en El Reventador llega a 6 000 mm. Ese volcán, un estratovolcán compartido con Napo, es uno de los más activos de Ecuador y permanece en erupción continua desde 2002; la del 3 de noviembre de ese año alcanzó el nivel 4 del índice de explosividad volcánica.

### Reservas y humedales

La Reserva de Producción de Fauna Cuyabeno, de casi 600 000 ha, ocupa buena parte del oriente provincial y alberga la zona intangible Cuyabeno-Imuya. Junto a ella figuran la Reserva Ecológica Cofán Bermejo, parte del Parque Nacional Cayambe Coca y el área de conservación municipal de La Bonita.

Dos sitios Ramsar protegen humedales: la Reserva Biológica Limoncocha, designada en julio de 1998, con 464 especies de aves registradas, y el complejo Cuyabeno-Lagartococha-Yasuní, de agosto del mismo año.

### Petróleo y tierra cultivada

El plan provincial recuerda que la Amazonía concentra el 99 % del petróleo ecuatoriano y reprocha al modelo extractivo no haber dejado ahorro ni capital fijo en el territorio. El Sistema de Oleoducto Transecuatoriano enlaza los campos amazónicos con la terminal de Esmeraldas.

Aun así, el agro y la ganadería suman cerca de la mitad de la economía local. El cacao es el cultivo estrella: 489 de las 1 391 unidades productivas encuestadas lo siembran. Lo acompañan palma aceitera, café, plátano, yuca y maíz.

### Fuentes

- [Gobierno Provincial de Sucumbíos: PDOT 2023-2038](https://www.sucumbios.gob.ec/wp-content/uploads/2025/05/PLAN-DE-DESARROLLO-Y-ORDENAMIENTO-TERRITORIAL-2023-2038.pdf)
- [Gobierno Provincial de Sucumbíos: rendición de cuentas](https://www.sucumbios.gob.ec/rendicion-de-cuentas/)
- [Congope: provincia de Sucumbíos](https://www.congope.gob.ec/provincia-de-sucumbios/)
- [INEC: Censo 2022, ficha de Sucumbíos](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Sucumbios.pdf)
- [Instituto Geofísico: volcán Reventador](https://www.igepn.edu.ec/reventador)
$c$ from public.provincias where slug = 'sucumbios' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Tungurahua ocupa el centro de la Sierra ecuatoriana y tiene a Ambato como capital. Se divide en nueve cantones: Ambato, Baños de Agua Santa, Cevallos, Mocha, Patate, Quero, San Pedro de Pelileo, Santiago de Píllaro y Tisaleo. Según el plan de desarrollo provincial, sus vecinas son Cotopaxi, hacia el norte y el oeste; Chimborazo, al sur; Pastaza y Napo, al este; y Bolívar, también al oeste. El CONGOPE le asigna unos 3 386 km², en la zona central del país.

### Entre dos cordilleras

La provincia ocupa la hoya del río Patate, cerrada por los ramales oriental y occidental de los Andes, que se unen al sur en el nudo Igualata-Sancajas. De esa geografía sale un relieve muy quebrado, con páramos, valles y laderas que descienden hacia la Amazonía. El río Ambato recibe al Pachanlica, y todo el conjunto pertenece a la cuenca alta del Pastaza.

El volcán Tungurahua alcanza unos 5 020 m, según el Instituto Geofísico. Su último periodo eruptivo se extendió de 1999 a 2016, y desde 2018 se lo clasifica como activo, no como en erupción. Los sismos de 1797, 1949 y 1968 figuran entre los más destructivos que ha sufrido la zona.

### Clima

Con altitudes que van de unos 1 200 a unos 5 000 m, las temperaturas medias oscilan entre 20 grados en las partes bajas y bajo cero en las más altas. En el valle interandino de Ambato, que se halla a unos 2 500 o 2 600 m, el plan provincial registra de 400 a 600 mm de lluvia al año, repartidos en dos temporadas: de marzo a junio y de octubre a noviembre.

### Habitantes y economía

El censo de 2022 contó 563 532 habitantes, el 40 % en zonas urbanas. Ambato reúne a 370 664 y Pelileo a 63 897. Un 84 % se identificó como mestizo y un 13,5 % como indígena; en la provincia viven los pueblos tomabela, chibuleo, quisapincha y salasaka, de habla kichwa.

La agricultura aporta el 27,61 % del valor agregado, la manufactura el 19,04 % y los servicios y el turismo el 13,80 %, según el plan provincial. El Gobierno Provincial destaca la fruta, la ganadería y los lácteos, y recuerda que desde los años setenta se impulsó el cultivo frutal. En la industria sobresalen el calzado, los textiles, las curtiembres, los alimentos y las carrocerías.

### Qué ver

Las áreas protegidas, es decir Llanganates, Sangay y la Reserva de Producción Faunística Chimborazo, suman 123 322 ha dentro de la provincia, el 36,43 % de su superficie. Entre los atractivos naturales, el plan menciona la cascada Inés María, en la parroquia Llígua, y las cascadas del río Verde, entre ellas el Pailón del Diablo. Desde los Llanganates baja el río Topo.

En la cultura popular destacan la Diablada de Píllaro y los Diablos de Marcos Espinel, que salen entre el 1 y el 6 de enero.

### Fuentes

- [Gobierno Provincial de Tungurahua: PDyOT 2019-2023](https://www.tungurahua.gob.ec/file/2020/07/PDyOT-TUNGURAHUA-2019-2023-Version-2.pdf)
- [INEC: Censo 2022, ficha de Tungurahua](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Tungurahua.pdf)
- [CONGOPE: provincia de Tungurahua](https://www.congope.gob.ec/provincia-de-tungurahua/)
- [Instituto Geofísico: volcán Tungurahua](https://www.igepn.edu.ec/tungurahua)
- [Gobierno Provincial de Tungurahua: cantones](https://www.tungurahua.gob.ec/cantones)
- [Gobierno Provincial de Tungurahua: demografía](https://www.tungurahua.gob.ec/demografia)
$c$ from public.provincias where slug = 'tungurahua' on conflict (provincia_id) do nothing;

insert into public.provincia_contenido (provincia_id, body) select id, $c$Zamora Chinchipe se separó de la antigua provincia de Santiago Zamora por un decreto legislativo del 28 de octubre de 1953, publicado en el Registro Oficial 360 del 10 de noviembre, y nació con tres cantones: Zamora, Chinchipe y Yacuambi. Hoy son nueve y la capital es Zamora. La provincia abarca unos 10 570 km² en el extremo austral de la Amazonía ecuatoriana, entre los relieves del Cóndor y la selva baja, a alturas de 815 a 2 800 m. Limita con Perú, con Loja y, según su plan de desarrollo, con Azuay y Morona Santiago.

### Una historia de fundaciones

Los shuar fueron los primeros habitantes. Zamora de los Alcaides se fundó el 6 de octubre de 1549, pero medio siglo después una sublevación shuar obligó a abandonarla; la ciudad actual se restableció el 12 de marzo de 1921. Desde mediados del siglo XIX llegaron familias saraguro y, desde los años veinte, colonos de Loja, Azuay y El Oro. Por eso entre los pueblos indígenas pesan los shuar y los saraguro, mientras los achuar son minoría. En Palanda y Chinchipe, la cultura Mayo-Chinchipe-Marañón, de más de 5 000 años, dejó evidencias de domesticación de cacao.

### Habitantes

El censo de 2022 contó 110 973 personas, frente a 90 407 en 2010. El 46,3 % vive en zonas urbanas; un 79,5 % se identificó como mestizo y un 18,9 % como indígena. Zamora (30 186) y Yantzaza (23 370) son los cantones más poblados.

### Lluvia, bosque y áreas protegidas

En Paquisha llueve de 2 600 a 2 800 mm al año; Chinchipe, el sector más seco, recibe de 900 a 1 200. En 2018 el bosque natural cubría el 71,24 % del territorio, aunque el pastizal pasó del 8,43 % en 2008 al 16,48 %. Los parques nacionales Podocarpus (124 340 ha en la provincia, compartido con Loja) y Yacuri, y la reserva biológica Cerro Plateado, forman el núcleo de las áreas protegidas del Estado, que suman el 18,5 % del territorio.

### Campo, minas y energía

En Chinchipe y Palanda se cultiva café, y el cacao orgánico se concentra en El Pangui. La ganadería es extensiva y de baja productividad: Palanda registra 31 903 bovinos y Chinchipe 24 268, con 4,1 litros de leche por vaca al día.

Fruta del Norte, de oro, está en Los Encuentros, cantón Yantzaza; la descubrió Aurelian Resources en 2006, Lundin Gold la compró en 2014 y se inauguró el 14 de noviembre de 2019. Mirador, de cobre, queda en Tundayme, cantón El Pangui, y produce desde junio de 2019. En 2010, sin embargo, la agricultura empleaba al 38,44 % de la población activa y las minas y canteras al 6,53 %.

### Qué ver y probar

El gobierno provincial propone cinco rutas turísticas. Yawi Sumak, en torno a Zamora, incluye 27 cascadas en la vía Loja-Zamora y el Jardín Botánico de América; Los Tepuyes suma las cascadas Las Lianas y El Sombrero. A la mesa llegan el caldo de corroncho, el repe y la papa china con queso; la cocina shuar aporta la chicha de yuca y de chonta.

### Fuentes

- [INEC: Censo 2022, ficha de Zamora Chinchipe](https://www.censoecuador.gob.ec/wp-content/uploads/2024/01/Info_Zamora_Chinchipe.pdf)
- [GAD Provincial de Zamora Chinchipe: PDOT 2019-2023](https://zamora-chinchipe.gob.ec/wp-content/uploads/2020/08/PDOT-2019-2023-ZAMORA-CHINCHIPE.pdf)
- [GAD Provincial de Zamora Chinchipe: PDOT 2014-2019](https://zamora-chinchipe.gob.ec/wp-content/uploads/2018/02/PDOT-ZAMORA-CHINCHIPE-2014-2019-m.pdf)
- [CONGOPE: Provincia de Zamora Chinchipe](https://www.congope.gob.ec/provincia-de-zamora-chinchipe/)
$c$ from public.provincias where slug = 'zamora-chinchipe' on conflict (provincia_id) do nothing;
